### ISSUE TITLE
Excessive maven build warnings: Failure to transfer...

### ISSUE THREAD

**Issue by ayoung012** [sarl/sarl#1000]
**Describe the bug**
When compiling a SARL project with Maven, specifically with the dependency:
```
        <dependency>
            <groupId>io.janusproject</groupId>
            <artifactId>io.janusproject.kernel</artifactId>
            <version>2.0.10.0</version>
        </dependency>
```
There are many warnings to do with eclipse dependencies of the janusproject kernel that drown out any meaningful output. One example error below:

```
[WARNING] Failure to transfer org.eclipse.platform:org.eclipse.equinox.common/maven-metadata.xml from http://download.eclipse.org/releases/2019-09/ was cached in the local repository, resolution will not be reattempted until the update interval of org.eclipse.ide.lastest has elapsed or updates are forced. Original error: Could not transfer metadata org.eclipse.platform:org.eclipse.equinox.common/maven-metadata.xml from/to org.eclipse.ide.lastest (http://download.eclipse.org/releases/2019-09/): Cannot access http://download.eclipse.org/releases/2019-09/ with type p2 using the available connector factories: BasicRepositoryConnectorFactory
```

All but one of these dependencies are from the `org.eclipse.platform` group of packages and it seems that they are unsupported by maven. Are these actually required for the janusproject kernel? My agents seem to compile fine with maven if I exclude them.

**To Reproduce**
1. Check out a basic project with maven support and janusproject kernel dependency, eg `git clone https://github.com/ayoung012/sarl-base-example.git`
2. `cd sarl-base-example`
3. `mvn compile`
4. See warnings

**Expected behavior**
No warnings, as can be acheived by adding the dependancy with some exclusions:
```
        <dependency>
            <groupId>io.janusproject</groupId>
            <artifactId>io.janusproject.kernel</artifactId>
            <version>${janus.version}</version>
            <exclusions>
              <exclusion>
                <groupId>org.eclipse.platform</groupId>
                <artifactId>org.eclipse.equinox.common</artifactId>
              </exclusion>
              <exclusion>
                <groupId>org.eclipse.platform</groupId>
                <artifactId>org.eclipse.equinox.preferences</artifactId>
              </exclusion>
              <exclusion>
                <groupId>org.eclipse.platform</groupId>
                <artifactId>org.eclipse.equinox.registry</artifactId>
              </exclusion>
              <exclusion>
                <groupId>org.eclipse.platform</groupId>
                <artifactId>org.eclipse.equinox.registry</artifactId>
              </exclusion>
              <exclusion>
                <groupId>org.eclipse.platform</groupId>
                <artifactId>org.eclipse.core.jobs</artifactId>
              </exclusion>
              <exclusion>
                <groupId>org.eclipse.platform</groupId>
                <artifactId>org.eclipse.core.contenttype</artifactId>
              </exclusion>
              <exclusion>
                <groupId>org.eclipse.platform</groupId>
                <artifactId>org.eclipse.equinox.app</artifactId>
              </exclusion>
              <exclusion>
                <groupId>org.eclipse.platform</groupId>
                <artifactId>org.eclipse.osgi</artifactId>
              </exclusion>
              <exclusion>
                <groupId>org.eclipse.platform</groupId>
                <artifactId>org.eclipse.core.runtime</artifactId>
              </exclusion>
              <exclusion>
                <groupId>org.eclipse.platform</groupId>
                <artifactId>org.eclipse.core.filesystem</artifactId>
              </exclusion>
              <exclusion>
                <groupId>org.eclipse.platform</groupId>
                <artifactId>org.eclipse.core.runtime</artifactId>
              </exclusion>
              <exclusion>
                <groupId>org.eclipse.platform</groupId>
                <artifactId>org.eclipse.core.resources</artifactId>
              </exclusion>
              <exclusion>
                <groupId>org.eclipse.platform</groupId>
                <artifactId>org.eclipse.text</artifactId>
              </exclusion>
              <exclusion>
                <groupId>org.eclipse.jdt</groupId>
                <artifactId>org.eclipse.jdt.core</artifactId>
              </exclusion>
            </exclusions>
        </dependency>
```

Is adding these exclusions the best way to avoid these warnings?

**System configuration:**
-- SARL version: 0.10.0
-- SARL compiler:
-  - [ ] Eclipse compiler without Maven	
-  - [ ] Eclipse compiler with Maven	
-  - [x] Maven compiler on the command line	
-  - [ ] sarlc compiler	
-- Java JDK version (with the manufacturer name): openjdk11
-- Operating System:	
-  - [x] Linux 64bits	
-  - [ ] Windows 64bits	
-  - [ ] MacOS 64bits	

**Additional context**

**Comment by gallandarakhneorg** [comment]
Dear @ayoung012.
It seems that we have to review the dependency tree and remove of the accesses to the Eclipse repository, since the SARL maven compiler is supposed to use the libraries that are provided on Maven Central server (and not on the Eclipse server).

**Comment by ayoung012** [comment]
I am unfamiliar with dependencies from the eclipse repo... I assume these dependencies are to aid development while editing in Eclipse?

**Comment by gallandarakhneorg** [comment]
Indeed, Eclipse Plugin Development and Maven are using two different systems for managing the dependencies, with two types of remote servers for delivering the Java libraries. The first is used within the Eclipse SARL environment forediting and compiling. The second is used for the command-line tools `sarlc` and `sarldoc`, and the "run-time" libraries such as Janus SRE.

I found that one of our base Maven module (`io.sarl.maven.bootiqueapp`) that is used for building the Janus SRE, also includes a module that is the SARL batch compiler. This module brings the "Eclipse" dependencies in the loop.

I will remove this invalid (and unnecessary) dependency in a coming commit.
