### ISSUE TITLE
Thread pool is blocking

### ISSUE THREAD

**Issue by gallandarakhneorg** [sarl/sarl#1002]
When launching the test `Bug976` on the Janus SRE with 10000 agents to be spawn, the test freezes around 2800 agents.

When the spawned agents fail into the `on Initialize` (exception for example), the test runs upto the 10000 agents.

**System configuration:**

- SARL version:	0.11
- SARL compiler:
- [x] Eclipse compiler without Maven	
- [ ] Eclipse compiler with Maven	
- [ ] Maven compiler on the command line	
- [ ] sarlc compiler	
- Java JDK version (with the manufacturer name):	1.8 Oracle
- Operating System:	
- [x] Linux 64bits	
- [ ] Windows 64bits	
- [ ] MacOS 64bits

**Comment by ngaud** [comment]
Unable to reproduce it with the lastest SARL version (release 0.11.0).
