### ISSUE TITLE
Expression with side effect is not allowed in guards

### ISSUE THREAD

**Issue by ssardina** [sarl/sarl#1009]
**Describe the bug**

Unecessary side-effect issue on behavior guards

**To Reproduce**

```
on E_MoveRandomly [occurrence.fromMe && (MT_getEntityState(occurrence.entity).routeLength > 0)] {
```

**Expected behavior**

Should work with no error

**Screenshot**
![image](https://user-images.githubusercontent.com/2368384/83943867-b10dc900-a842-11ea-8387-a015ae6b4fa7.png)

**System configuration:**
-- SARL version:	0.10.0
-- SARL compiler:	0.10.0
-  - [x] Eclipse compiler without Maven	
-  - [ ] Eclipse compiler with Maven	
-  - [ ] Maven compiler on the command line	
-  - [ ] sarlc compiler	
-- Java JDK version (with the manufacturer name):	1.8 Oracle
-- Operating System:	
-  - [x] Linux 64bits	
-  - [ ] Windows 64bits	
-  - [ ] MacOS 64bits	

**Additional context**

**Comment by ssardina** [comment]
Related issues #335 and #322

**Comment by ssardina** [comment]
I tried to do the usual "trick" and extract the occurrence, but still complains of side-effect on guard:

```
	on E_MoveRandomly [{
		var entity = occurrence.entity;
		val l = MT_getEntityState(entity).routeLength;
		(l > 0)
	}] {
```

So I think it does not like `MT_getEntityState(entity)` regardless of `occurrence`. Now, that seems to be quite a bit of a limitatation and it used to work well, at least with 0.8.6 last time I had this code.

Am I missing something here?

**Comment by gallandarakhneorg** [comment]
Dear @ssardina.
A quick fix is:
```sarl
on E_MoveRandomly {
    if (occurrence.fromMe && (MT_getEntityState(occurrence.entity).routeLength > 0)) {
```

**Comment by gallandarakhneorg** [comment]
Dear @ssardina. Could you provide a link to a git or a copy of the failing code. In this way, I will be able to determine why the SARL compiler has not detected your function as pure; and possibly patch the compiler.

**Comment by ssardina** [comment]
Thanks a lot @gallandarakhneorg , I see now. The check is good and the @Pure directive is a good middle ground to keep the functionality check but also allow the programer to override that with a clear annotation. For my future reference (and for my future students) I have summarized your explanation and put it in [my doc that I have for SARL](https://gist.github.com/ssardina/ba59838bd6f2c2a64896e79533f35054#expression-with-side-effect-is-not-allowed-in-guards).

The system that I am working is [this one](https://github.com/ssardina-agts/agtcity-sarl-mw). However, that code is still not there, it is work in progress, I will work now and push it later to a branch for you to have access if that helps.

But with the very useful info you gave me I am doing some experiments and I can tell you a few things:

1. The `@Pure` works, even when it is specified only in the Capacity definition only (not in its implementation at the Skill).

2. If I don't put the `@Pure` then:

```java
on E_EntitySensed [
	MT_getEntityState(occurrance.entityName).routeLength == 0 &&
		MT_getEntityState(occurrance.entityName).facility !== null &&
		state.getShops().containsKey(MT_getEntityState(occurrance.entityName).facility) &&
		MT_getEntityState(occurrance.entityName).lastAction.type != "buy"
	] {
```

is totally fine and does not complain, but the "equivalent" (optimize version to extract the state once):

```java
on E_EntitySensed [
	{
	val entity = MT_getEntityState(occurrance.entityName)
	entity.routeLength == 0 && entity.facility !== null &&
		state.getShops().containsKey(entity.facility) && entity.lastAction.type != "buy"
}
	] {
```

does complain about side-effects. Here `occurrance` happens in the RHS.

In any case, I suspect this is not per se a bug. SARL tries to figure out if it is pure, but as you said my name convention would never help...

Not sure if the two different scenarios above make any difference. Why does the second one complains about side-effect when occurrence is used in the RHS?

**Comment by gallandarakhneorg** [comment]
Thank you for the code example. I think a bug may still exist that avoid SARL to properly detect the purity of the expression. We will use your inputs to set up a complete test.

**Comment by ssardina** [comment]
Excellent, glad I could help. Nonetheless, in my case, I marked the functions with `@Pure` as I think it's good anyways to state explicitly what is the expected nature of the functions.

**Comment by gallandarakhneorg** [comment]
According to the commit above, I confirm that the SARL compiler is providing the error "Side effect not allowed in guards" as expected.

The cause of the error is discussed above (not-standard function naming convention), and could be manually solved by attaching explicitly the `@Pure` annotation to the `MT_getEntityState` function.

I have moved this issue from "Bug" to "FAQ" and "Documentation" tags in order to upgrade the documentation sources with some information on this case.

**Comment by ssardina** [comment]
Excellent. Agree. Yes I have put `@Pure` in my methods, as they are also good as documentation of what is expected from the methods.

Indeed would be good to have this in the doc.  I wonder whether a section with the possible errors one may get in SARL and an explanation (as you have done numerous times here to me) would be best. This is what I am doing here:

https://gist.github.com/ssardina/ba59838bd6f2c2a64896e79533f35054#expression-with-side-effect-is-not-allowed-in-guards

**Comment by gallandarakhneorg** [comment]
Indeed, I'm preraring a new section for the FAQ and the general documentation related to the pure functions.

I have proposed Issue #1010 in order to create a documentation's page that is dedicated to the list of all the possible compilation errors from the SARL compiler.

**Comment by gallandarakhneorg** [comment]
Dear @ssardina, regarding your comment about the list of all the errors that could be given by SARL, I have added this [page](http://www.sarl.io/docs/official/reference/CompilerErrors.html) for SARL, and this [page](http://www.sarl.io/docs/official/tools/Janus.html#3-list-of-errors-and-warnings) for Janus.
Both of them are accessible from several points into the documentation pages.

**Comment by ssardina** [comment]
That is outstanding @gallandarakhneorg ! Really good and useful. I will add those links to my wiki as they will surely come useful!

Will let you know if I found that more info can be given or something is missing. It will happen once I encounter some of those problems I guess.

One thing that I can think of is to list there the name for disabling the warning via `@SuppressWarnings(..)` directive.

The only place I found a list of them is here in the source code:

https://github.com/sarl/sarl/blob/master/main/coreplugins/io.sarl.lang/src/io/sarl/lang/validation/IssueCodes.java

If anything maybe that page can refer to it as well, or have another column with the name to supress (not all of them have though)

THANKS!

**Comment by gallandarakhneorg** [comment]
I will change the tables into the documentation. Because the "code" column provides the code for `@SuppressWarnings`. But, it is incomplete.

**Comment by ssardina** [comment]
Yes you are right, wonderful, I can see them all now!

I can see `invalid_inner_expression` now for example! Now let me understand more:

1. If I add `@SupressWarnings("invalid_inner_expression")`, then the compiler won't complain anymore about what this issue is all about? mmm

2. The text for it says: _"has side effect, i.e. it modifies the state of the current"_ Should it say "may have side effects, i.e., it may modify the state of the current"?

**Comment by gallandarakhneorg** [comment]
Dear @ssardina, I have written my reply in Issue #1010
