### ISSUE TITLE
Create a documentation for all the possible errors from the SARL compiler

### ISSUE THREAD

**Issue by gallandarakhneorg** [sarl/sarl#1010]
It may be usefull to provide a list of all the possible errors that could be provided by the SARL compiler, and give explaination on them.

**Comment by gallandarakhneorg** [comment]
See http://www.sarl.io/docs/official/reference/CompilerErrors.html

**Comment by gallandarakhneorg** [comment]
And for Janus: http://www.sarl.io/docs/official/tools/Janus.html#3-list-of-errors-and-warnings

**Comment by gallandarakhneorg** [comment]
The "code" column into the error list tables provides the code for `@SuppressWarnings`. But, it is incomplete.

**Comment by gallandarakhneorg** [comment]
From @ssardina:
> can see `invalid_inner_expression` now for example! Now let me understand more:
> 
> 1. If I add `@SupressWarnings("invalid_inner_expression")`, then the compiler won't complain anymore about what this issue is all about? mmm
> 2. The text for it says: _"has side effect,_


1. Yes and no. Indeed, only the issues that have a level "configurable" could be ignored with `@SuppressWarnings`. By design choice, several issues are marked a full-time error and warnings without the capability to be ignored. If an issue could be ignored, using `@SuppressWarnings` makes the SARL compiler to skip the issue (it is the same behavior as with the Eclipse Java compiler at least).

2. I have updated the general introduction text on the page, as well as the text of the issue.

**Comment by ssardina** [comment]
Excellent, it is now very clear the doc, explaining what configurable is, etc. great.

Just on the line of "configurable": "by the SARL developers himself. " --> "by the SARL developers **themselves**. "

Thanks, great addition!

**Comment by ssardina** [comment]
@gallandarakhneorg , I want to follow up on error 28a:

> Message: Possible invalid usage of ‘occurrence’. A impure function is detected into the sequence of calls on ‘occurrence’. Because a impure function has a possible side effect and side effect is not allowed on ‘occurrence’, it may cause an unexpected or invalid running behavior. You have to ensure by yourself that the usage of ‘occurrence’ is valid

See the code that is giving me this warning (that I want to get rid of):

```java
on E_SetupPlayer [occurrence.agentName == this.agentName] {
		debug("Starting to register new behaviors and skills using {0} file", occurrence.configFile)

		val teamRoles = occurrence.teamRoles
```

and the definition of the event is  just:

```
event E_SetupPlayer {
	var agentName : String
	var configDir : String
	var configFile : String
	var teamRoles : Map<String, Integer>
	var centralBuilder : String

	new(agentName : String, configDir : String, configFile : String, teamRoles : Map<String, Integer>, centralBuilder : String) {
		this.agentName = agentName
		this.configDir = configDir
		this.configFile = configFile
		this.teamRoles = teamRoles
		this.centralBuilder = centralBuilder
	}
}
```

Now why a simple assignment like:

```
		val teamRoles = occurrence.teamRoles
```

would give this warning, I am not using any (unpure) function at all. I don't even know how one would re-write such assignment.

Thanks!

**Comment by ssardina** [comment]
I guess this would be 28c and is missing in the compiler error list:

`Possible invalid usage of 'occurrence'. The value of the feature 'occurrence' or one of its component is used as an argument of a function. This function is not marked as a pure function, i.e. without side effect. Because side effect is not allowed on 'occurrence', it may cause an unexpected or invalid running behavior. You have to ensure by yourself that the usage of 'occurrence' is valid.`

@gallandarakhneorg I would re-open this one rather than create a new one, but I cannot re-open issues it seems

**Comment by gallandarakhneorg** [comment]
See new

**Comment by ssardina** [comment]
Great. I am assuming this will be delopyed to the web page later (as I cannot see it now in the doc)

**Comment by gallandarakhneorg** [comment]
Yes, my changes are committed in a separated branch on Github, until this branch is compiling and passing the unit tests. As soon as it is ok, I will merge the branch to the master and synchronize the website.
