### ISSUE TITLE
Invalid warning "Possible invalid usage of ‘occurrence’"

### ISSUE THREAD

**Issue by gallandarakhneorg** [sarl/sarl#1013]
@gallandarakhneorg , I want to follow up on error 28a:

> Message: Possible invalid usage of ‘occurrence’. A impure function is detected into the sequence of calls on ‘occurrence’. Because a impure function has a possible side effect and side effect is not allowed on ‘occurrence’, it may cause an unexpected or invalid running behavior. You have to ensure by yourself that the usage of ‘occurrence’ is valid

See the code that is giving me this warning (that I want to get rid of):

```java
on E_SetupPlayer [occurrence.agentName == this.agentName] {
		debug("Starting to register new behaviors and skills using {0} file", occurrence.configFile)

		val teamRoles = occurrence.teamRoles
```

and the definition of the event is  just:

```
event E_SetupPlayer {
	var agentName : String
	var configDir : String
	var configFile : String
	var teamRoles : Map<String, Integer>
	var centralBuilder : String

	new(agentName : String, configDir : String, configFile : String, teamRoles : Map<String, Integer>, centralBuilder : String) {
		this.agentName = agentName
		this.configDir = configDir
		this.configFile = configFile
		this.teamRoles = teamRoles
		this.centralBuilder = centralBuilder
	}
}
```

Now why a simple assignment like:

```
		val teamRoles = occurrence.teamRoles
```

would give this warning, I am not using any (unpure) function at all. I don't even know how one would re-write such assignment.

Thanks!

_Originally posted by @ssardina in https://github.com/sarl/sarl/issues/1010#issuecomment-646935197_

**Comment by gallandarakhneorg** [comment]
With version 0.12, I don't have the same warnings as the one you mention. I have the following warnings messages:

1. On "occurrence.configFile", I have "Possible invalid usage of ‘occurrence’. [...] function argument"
2. On "occurrence.teamRoles", I have "Possible invalid usage of ‘occurrence’. [...] copied to local variable"
3. On "val teamRoles", I have "Unused local variable".

This behavior was validated by unit tests and direct edition into the Eclipse SARL product.

@ssardina, have you more lines of code than the provided ones, especially after the assignment that you have mentionned?

**Comment by ssardina** [comment]
Ohh I am testing on 0.10.0.

I realize there is a 0.11.0 stable (I prefer to use "stable" releases).

I don't think it will help you much but here is the full behavior code:

```
	on E_SetupPlayer [occurrence.agentName == this.agentName] {
		debug("Starting to register new behaviors and skills using {0} file", occurrence.configFile)

		val teamRoles = occurrence.teamRoles

		try {
			var config : JSONObject = new JSONObject(
				new String(Files.readAllBytes(Paths.get(occurrence.configDir, occurrence.configFile)))
			)

			var behaviors : JSONArray = config.getJSONArray("behaviors")
			var skills : JSONArray = config.getJSONArray("skills")
			var teamRole = config.getString("teamRole")

			// team role tells us this agents responsibility
			assertFirst("team_role(?)", teamRole)
			assertFirst("central_builder(?)", occurrence.centralBuilder) // central builder

			if (behaviors !== null) // if there are behaviors
				registerNewBehaviors(myAgent, behaviors, teamRoles)

			if (skills !== null) // if there are skills
				registerNewSkills(skills)

		} catch (e : IOException) {
			e.printStackTrace()
		}

		// Our agent is now setup. We can now make a move for the first percept
		//emit(new E_SensedEnvironment => [firstStep = true])
		emit(new E_PlayerReady())

		// Start sensing for this agent
		emit(new E_SenseEnvironment())
	}

```

**Comment by ssardina** [comment]
See it even complains on the ocurrence. as argument of `debug`:

![image](https://user-images.githubusercontent.com/2368384/85215088-e247d680-b3b6-11ea-95ea-2d972db68faa.png)

**Comment by gallandarakhneorg** [comment]
Soory, I didn't do a complete analysis of the situation.
The warning on `occurrence.configFile` could be considerd as a bug into the SARL compiler. Indeed, in this context the type of `configFile` is a unmodifiable type. So that, there is no change for the called function (here `debug`) to change the fields' values of `occurrence`.

**Comment by ssardina** [comment]
Excellent, happy to help with "testing" and "breaking things"  (the easy part...) ;-)

Now, per se, `occurrence.configFile` is a `String` field in the event object and COULD be potentially changed right? The thing is that `debug` does not change that at all. Is this what you mean? But how does SARL know if a given function (`debug` here) changes or not an argument? It is a String object so it can be changed right?

**Comment by gallandarakhneorg** [comment]
> Excellent, happy to help with "testing" and "breaking things" (the easy part...) ;-)
> 
> Now, per se, `occurrence.configFile` is a `String` field in the event object and COULD be potentially changed right? The thing is that `debug` does not change that at all. Is this what you mean? But how does SARL know if a given function (`debug` here) changes or not an argument? It is a String object so it can be changed right?

A `String` object is immutable by definition (same as in Java). Currently, except if a SARL function is declared as `@Pure`, SARL assumes it is impure. But, this assumption may be wrong. That's why the warning is make: notify the developper that a problem may exists.


> Ohh is is the case that any changes to `String` will actualy generate a new `String`, not just change the referenced one? So yes any String cannot be changed per se. But this is just because it is a String, this reasoning does not apply in general.

It applies to all the types that are known to be immutable. There is a couple of them: Number, URL, UUID, etc.

> So are you saying that the SARL compiler should never care about Strings passed as arguments?

Yes. Because it cannot have synchronization issue with them.

**Comment by gallandarakhneorg** [comment]
The SARL validator is now checking if the called feature is of immutable type ([list of immutable types](https://github.com/sarl/sarl/blob/master/main/coreplugins/io.sarl.lang/src/io/sarl/lang/typesystem/DefaultImmutableTypeValidator.java)). If it is the case, no warning is generated because there is no chance to have a side-effect on the usage of `occurrence`.
