### ISSUE TITLE
Add search engine in the website's documentation.

### ISSUE THREAD

**Issue by gallandarakhneorg** [sarl/sarl#1017]
It is still hard to find information into the documentation.
A search toolbar may be helpfull.

Since the SARL website is pure HTML without PHP. We have to determine if it is possible to include a search engine based on JavaScript.

_Originally posted by @ssardina and @gallandarakhneorg in https://github.com/sarl/sarl/issues/208#issuecomment-647315256_

**Comment by gallandarakhneorg** [comment]
See https://blog.webjeda.com/instant-jekyll-search/

**Comment by ssardina** [comment]
What about just adding a Google search bar that does

`site:http://www.sarl.io/docs <what you want to search>"

**Comment by gallandarakhneorg** [comment]
Add seach bar was added to the `sarl.io` website that is ased on Google Custom Search Engine. Links to the search bar are added in the toolbar and the footer.

**Comment by ssardina** [comment]
This is a great addition @gallandarakhneorg !! I just searched "variadic" which I always have trouble finding about and the search gave me perfect results! THANKS!
