### ISSUE TITLE
Empty event after emitToAgents call

### ISSUE THREAD

**Issue by yannic7** [sarl/sarl#1024]
**Describe the bug**
I created a GUI for my agent application and I try to emit an "SetupSettings" event (exactly like in the fireworks example) using emitToAgents. However, the "on SetupSettings { ... }" section in my "Organizer" agent never runs.

**To Reproduce**
This is inside my GUI controller
```
@FXML
def startMatch() {
    rounds = Integer.valueOf(roundNum.getText())
    matches = Integer.valueOf(gameNum.getText())

    var ^event : SetupSettings = new SetupSettings(s1, s2, rounds, matches)
    this.launchedAgent = UUID::randomUUID
    startAgentApplication(typeof(Organizer), this.launchedAgent) [
        ^event.emitToAgents
    ]
}
```

This is inside my agent:
```
agent Organizer {
uses Lifecycle, Schedules, DefaultContextInteractions, Logging

var s1 : String
var s2 : String
var matches : int
var rounds : int

on SetupSettings {
    this.s1 = occurrence.s1
    this.s2 = occurrence.s2
    this.matches = occurrence.matches
    this.rounds = occurrence.rounds
    info("s1 = " + this.s1 + ", s2 = " + this.s2)
    info("matches = " + this.matches + ", rounds: " + this.rounds) 
}
```

**Expected behavior**
The "on SetupSettings" event should run.

**System configuration:**
-- SARL version: 0.11.0	
-- SARL compiler: 0.11.0
-  - [ ] Eclipse compiler without Maven	
-  - [x] Eclipse compiler with Maven	
-  - [ ] Maven compiler on the command line	
-  - [ ] sarlc compiler	
-- Java JDK version (with the manufacturer name): 1.8.0_261	
-- Operating System: Windows 10 x64	
-  - [x] Linux 64bits	
-  - [ ] Windows 64bits	
-  - [ ] MacOS 64bits

**Comment by ngaud** [comment]
Are you sure you registered your Organizer agent in the UI shared space ?
Something like (see initialize of launchingarea agent in fireworks demo) : 

on Initialize [!occurrence.parameters.empty] {
		loggingName = "LaunchingArea-" + this.ID
		var ctrl = occurrence.parameters.get(0) as FireworksFxViewerController
		ctrl.UISpace.register(asEventListener) // registering the LaunchingArea agent on the UI space
		ctrl.listenAndDraw(grid)
		info("Finishing initialization of Launching Area")
	}
The space is the support for event distribution, if agents/communicating objects are not in the same space, they cannot exchange events.

That could be one of the reason of your problem.

If you effectively register your agent in the UI space, in this case, we will need more source code to investigate your problem.

**Comment by yannic7** [comment]
That's it! Thank you so much, I totally forgot about that.
