### ISSUE TITLE
Small bug in the SARL documentation, page Run SARL Agent from a Java Program

### ISSUE THREAD

**Issue by ngaud** [sarl/sarl#1025]
**Describe the bug**
Small bug in the SARL documentation at the bottom of this page : [Run SARL Agent from a Java Program](http://www.sarl.io/docs/official/gettingstarted/RunSARLAgentJava.html )
The markdown is not well interpreted.

In the paragrpah starting by "The Janus platform enables to launch a single agent at start-up. If you want to launch more agents, please read the next section...."

**Comment by gallandarakhneorg** [comment]
The new markdown interpreter has problem when parsing the code block depending on the used syntax, i.e. with the backquote syntax, or with the tab spaces. The backquote syntax seems to be propertly parsed; The tab-based syntax not.
