### ISSUE TITLE
All kernels threads are not terminated in the Boids Demo

### ISSUE THREAD

**Issue by ngaud** [sarl/sarl#1030]
Even if we manage to send a Die event leading to a call to killMe for every agents, it still remains few running processes preventing the Janus Kernel from stopping.

Investigate to determine if it is a demo bug or more general bug related to process termination in Janus kernel.

**Comment by gallandarakhneorg** [comment]
Is it the demo that is embedded into the SARL product, or your demo for the IA54 lecture?
