### ISSUE TITLE
Parenthesis not closed in SARLAgentMainLaunchConfigurationTab

### ISSUE THREAD

**Issue by ngaud** [sarl/sarl#1036]
On the main tab of the launch configuration in the Radio button group named "identifier for the root context"
parenthesis of options 1 and 3 are opened but not closed.

**Comment by gallandarakhneorg** [comment]
![Capture d’écran de 2020-11-28 14-53-11](https://user-images.githubusercontent.com/4200154/100517284-d7754700-3189-11eb-8711-31b2e23fb5b8.png)
