### ISSUE TITLE
On Windows, problem with the management of CLI options /log and /boot-type are in agent initialization parameters

### ISSUE THREAD

**Issue by ngaud** [sarl/sarl#1037]
On Windows 10, JVM openjdk 8 the agent's intialization parameters also contains /log=all, /boot-type=default
and probably some others options according to the user choice in the launch configuration

**Comment by gallandarakhneorg** [comment]
It seems that the Bootique API does not care about the standards of command-line option format, e.g. `-` on Unix and `/` on Windows. All the command-line options inside the SARL product are now formatted according to the Unix standard.
