### ISSUE TITLE
getContext is null after a join and it must not be

### ISSUE THREAD

**Issue by ngaud** [sarl/sarl#1038]
var cID = occurrence.subContextID
		var sID = occurrence.subContextDefaultSpaceID 
		join(cID, sID)
		// comspace = getContext(occurrence.subContextID).getSpace(sharedSpaceID)
		var contextTJustJoined = getContext(cID) 
		assert(contextTJustJoined !== null) ---> this assert must always be true considering that the corresponding context has jsut been joined but sometimes it is null
		comspace = contextTJustJoined.getOrCreateSpaceWithSpec(typeof(OpenEventSpaceSpecification),
			sharedSpaceID)	

Probably related to the use of contextreference in AgentLife and their corresponding lock management

**Comment by gallandarakhneorg** [comment]
Possible cause to explore: the inner context with identifier `cID` is not created into the context repository because it is created on-the-fly by the agent with identifier `cID`. Then, the `join` function cannot retrieve the context instance through the context repository.
