### ISSUE TITLE
Corrupted product for MacOS

### ISSUE THREAD

**Issue by gallandarakhneorg** [sarl/sarl#1051]
**Describe the bug**
After downloading a fresh SARL on my MacOS Catalina, the system indicates that the application is corrupted.

**To Reproduce**
1. Open on MacOS
2. Download the MacOS SARL product from the download page
3. After downloading, double-click on the app.

**Expected behavior**
Application should starts.

**Screenshots**
<img width="300" alt="macos" src="https://user-images.githubusercontent.com/4200154/105148907-3492d680-5b03-11eb-9f5c-c8767a769459.png">

**System configuration:**
-- SARL version: `0.11`
-- Java JDK version (with the manufacturer name): `JDK 1.8 202 OpenJDK`
-- Operating System:	
-  - [ ] Linux 64bits	
-  - [ ] Windows 64bits	
-  - [X] MacOS 64bits

**Comment by srodriguez** [comment]
Hi. When SARL is compiled locally in a Mac the product created works perfectly.

My environment 
MacOs Big Sur 11.1
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_212-b04)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.212-b04, mixed mode)

**Comment by gallandarakhneorg** [comment]
I confirm that a version that is locally compiled is running, after setting the VM into the `eclipse.ini` file.

My environment:
* MacOs Big Sur 11.1 inside VirtualBox
* Oracle jdk version "1.8.0_202"

**Comment by gallandarakhneorg** [comment]
Significant differences between the version generated on MacOS (given by @srodriguez) and the one generated on Linux (given by @gallandarakhneorg) are in files:
* `Eclipse.app/Contents/Eclipse/p2/org.eclipse.equinox.p2.engine/.settings/*.pref` (contains the login name of the user who compiled);
* Several Jar files are different from binary point of view but it seems to be not significant because I could extract the Jar files' content.

**Comment by gallandarakhneorg** [comment]
I found a quick fix by adding the path to your JVM into the Eclipse configuration.

1. Locate the folder in which your JVM (not the standard Mac JRE) is installed, e.g. `/Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home/bin`
2. The previous folder must contains the tools `javac` and `java`
3. Open the folder in which the SARL `Eclipse.app` was copied
4. Right-click on `Eclipse.app` and select `Show Package Contents`
5. Move to `Contents/Eclipse`
6. Open `eclipse-sarl.ini` with a text editor
7. Add the following lines into the file or update the lines if they exist (there is a line break that must be inside the file content):
```
-vm
/Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home/bin
```
8. Save and start the SARL IDE.

An complete example of the `eclipse-sarl.ini` file is:
```
-startup
../Eclipse/plugins/org.eclipse.equinox.launcher_1.5.600.v20191014-2022.jar
--launcher.library
../Eclipse/plugins/org.eclipse.equinox.launcher.cocoa.macosx.x86_64_1.1.1100.v20190907-0426
-vm
/Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home/bin
-vmargs
-Xms256m
-Xmx1g
-XstartOnFirstThread
-Dorg.eclipse.swt.internal.carbon.smallFonts
```

**Comment by gallandarakhneorg** [comment]
Version 0.11 that could be downloaded from the SARL website, seems to have a large set of differences compared to the version 0.11 compiled by me and @srodriguez.

** Version 0.11 for MacOS on the SARL download page is still damaged **

**Comment by gallandarakhneorg** [comment]
Summary of my tests:

| Compilation type | Compil. OS | File transfer | Status |
| --- | --- | --- | --- |
| Local - @srodriguez  | MacOS | n/a | Ok |
| Local - @gallandarakhneorg | MacOS | n/a | Ok |
| Local - mvn install | Linux | USB disk | Ok |
| Local - mvn release | Linux | USB disk | Ok |
| n/a | n/a | Download with Chrome on Linux + USB disk | Ok |
| n/a | n/a | Download with Safari on MacOS | Corrupted |

I have reach my max knowledge about MacOS software use. Any idea?

**Comment by gallandarakhneorg** [comment]
I found a [post](https://osxdaily.com/2019/10/24/fix-install-macos-application-damaged-cant-be-used-error-mac/) on Internet that indicates we could remove a `.plist` file for solving this issue.

Now SARL is starting well!

So, it means that there is some issue with the certification of the application on new MacOS.

**Comment by gallandarakhneorg** [comment]
Next actions:

* Update the FAQ
* Update SARL 0.12 in order to properly generate the `.plist` file.
* Provide a easy way for setting up the JVM into the `eclipse-sarl.ini` file.
