### ISSUE TITLE
404 Error

### ISSUE THREAD

**Issue by shahshakir** [sarl/sarl#1053]
**Description of your issue:**
Describe your issue here/
The Links for  following projects (used SARL) generate **404 error**:
Jaak Simulation Library
SARL Elevator Simulator Controller

I hope that you will see the matter.

**Comment by gallandarakhneorg** [comment]
Dear @shahshakir.

Thank you for your feedback.

The broken URLs on the Bitbuckets repositories are fixed.

All the best.
