### ISSUE TITLE
Add FAQ entries for the deprecated API

### ISSUE THREAD

**Issue by gallandarakhneorg** [sarl/sarl#1058]
Several features of the SARL API were deprecated. There is a documentation into the API documentation that is attached to the `@Deprecated` annotation and describes the possible replacements.

However, these explanations are not enough to understood how to migrate a SARL From a previous version of the API to the lastest one.

I propose to write a section of the FAQ that is dedicated to these changes.

**Comment by ssardina** [comment]
I can help a bit with that by documenting everything I bumped into in the process of upgrading my SARL systems to 0.11.0.

I have collected 2 already and I will be writing them here:

https://gist.github.com/ssardina/ba59838bd6f2c2a64896e79533f35054#changes-sre-2x-to-sre-3x

Once done you can take them to the official SARL doc.
