### ISSUE TITLE
Add the functions addSkill and removeSkill in the agents

### ISSUE THREAD

**Issue by gallandarakhneorg** [sarl/sarl#106]
It may be user-friendly to have the following functions in the agent.

The first function permits to add a skill very easily at the developer point of view:
```java
protected void addSkill(Skill s) {
  for(Class<? extends Capacity> type : extractCapacityInterfaces(s)) {
    setSkill(type, s);
  }
}
```

The second function permits to remove a skill very easily at the developer point of view:
```java
protected void removeSkill(Skill s) {
  for(Class<? extends Capacity> type : extractCapacityInterfaces(s)) {
    if (getSkill(type)==s) clearSkill(type);
  }
}
```

An extension of this proposal may be to add into the agents:
```java
protected Collection<Skill> getSkills() {
  return new AbstractCollection<Skill>() {
    public void add(Skill e) {
      addSkill(e);
    }
    public void remove(Skill e) {
      removeSkill(e);
    }
  }
}
```

This last addition enables to write the following code in SARL (because of the operator definition in Xbase):
```java
agent A {
  on Initialize {
    var s = new MySkill
    skills += s
    skills -= s
  }
}
```

**Comment by srodriguez** [comment]
The problem with this solution is that in might replace skills on the capacity's hierarchy implicitly.
This may cause some confusion and it is error prone.

**Comment by gallandarakhneorg** [comment]
Duplicate of #438.
