### ISSUE TITLE
Clashes of variable when using =>  in ECLIPSE

### ISSUE THREAD

**Issue by ssardina** [sarl/sarl#1060]
**Describe the bug**

![image](https://user-images.githubusercontent.com/2368384/107863275-14a6c680-6ea7-11eb-8f6a-ba79ad81b94d.png)

See the entity in the emission of the event, should NOT be the one in the agent, but seems ECLIPSE is thinking it is that one rather the data in the event class.

Error is in the IDE and even in CLI:

```
[ERROR] Failed to execute goal io.sarl.maven:sarl-maven-plugin:0.11.0:compile (default-compile) on project agtcity-sarl-base: Assignment to final variable [/home/ssardina/git/soft/agents/MAC-AgtCity/2018-rmit/agtcity-sarl-base.git/src/main/sarl/au/edu/rmit/agtgrp/agtcity/sarl/agents/dummy/SuperSingleAgent.sarl:245] -> [Help 1]
```

**Expected behavior**

No error should be given.

**System configuration:**
-- SARL version:	0.11.0
-- SARL compiler:	0.11.0
-  - [] Eclipse compiler without Maven	
-  - [X] Eclipse compiler with Maven	
-  - [X ] Maven compiler on the command line	
-  - [ ] sarlc compiler	
-- Java JDK version (with the manufacturer name):	1.8
-- Operating System:	
-  - [x] Linux 64bits	
-  - [ ] Windows 64bits	
-  - [ ] MacOS 64bits	

**Additional context**

**Comment by gallandarakhneorg** [comment]
I assume that the event `E_MoveRandomly` contains the declaration of a field named `entity`.

A quick fix should be: `new E_MoveRandomly => [this.entity = entityName]`.

**Comment by ssardina** [comment]
Yes, correct. Interesting this does not give errors:
Interestingly, before I read your reply, I tried `this.entity` and did not work, it says that `entity` is not a field of the agent, fair enough.

However, `it.entity` does work! and when I click it navigate to the event as expected.

**Comment by ssardina** [comment]
So, I am assuming this is the intended use and one should use `it.<variable>` to disambiguate if needed?

**Comment by gallandarakhneorg** [comment]
You're right.
For who will be interested about the base reason, the compiler searches for a variable of name `v` following the steps:
1. if a local variable named `v` is accessible, it is used;
2. if an attribute for `it`, i.e. `it.v`, it is used;
3. if an attribute for `this`, i.e. `this.v`, it is used;
5. if a variable `v` is statically imported, it is used.

**Comment by ssardina** [comment]
Great, have added this to my FAQ
