### ISSUE TITLE
The POM for org.mule.tools.maven:mule-maven-plugin:jar:3.3.2 is missing, no dependency information available

### ISSUE THREAD

**Issue by testtestvaranasi** [sarl/sarl#1065]
Hi,
   I am getting the following issue while running the CI/CD Pipeline.

Running with gitlab-runner 13.8.0 (775dd39d)
  on devops SriUZLNC
Resolving secrets
00:00
Preparing the "shell" executor
00:00
Using Shell executor...
Preparing environment
00:01
Running on USAWSTDCI001...
Getting source from Git repository
00:03
Fetching changes with git depth set to 50...
Reinitialized existing Git repository in C:/GitLab-Runner/builds/SriUZLNC/0/nvent-it-enterprise-solutions/devops/test-e-distributor/.git/
Checking out 128b7c1d as develop...
git-lfs/2.13.2 (GitHub; windows amd64; go 1.14.13; git fc664697)
Skipping Git submodules setup
Executing "step_script" stage of the job script
00:03
$ echo "Code Check the project with maven"
Code Check the project with maven
$ mvn -version
Apache Maven 3.5.3 (3383c37e1f9e9b3bc3df5050c29c8aff9f295297; 2018-02-24T14:49:05-05:00)
Maven home: C:\Program Files\Apache Software Foundation\apache-maven-3.5.3\bin\..
Java version: 1.8.0_241, vendor: Oracle Corporation
Java home: C:\Program Files\Java\jdk1.8.0_241\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows server 2019", version: "10.0", arch: "amd64", family: "windows"
$ mvn $MAVEN_CLI_OPTS clean package -Pcode-check -Du=$ap_user -Dp=$ap_pw4
[INFO] Scanning for projects...
[WARNING] The POM for org.mule.tools.maven:mule-maven-plugin:jar:3.3.2 is missing, no dependency information available
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Unresolveable build extension: Plugin org.mule.tools.maven:mule-maven-plugin:3.3.2 or one of its dependencies could not be resolved: Failure to find org.mule.tools.maven:mule-maven-plugin:jar:3.3.2 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced @ 
[ERROR] Unknown packaging: mule-application @ line 11, column 13
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project 3f60c974-c1ba-49b4-8fd4-c66cb8afce0d:e-distributor:1.0.0 (C:\GitLab-Runner\builds\SriUZLNC\0\nvent-it-enterprise-solutions\devops\test-e-distributor\pom.xml) has 2 errors
[ERROR]     Unresolveable build extension: Plugin org.mule.tools.maven:mule-maven-plugin:3.3.2 or one of its dependencies could not be resolved: Failure to find org.mule.tools.maven:mule-maven-plugin:jar:3.3.2 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 2]
[ERROR]     Unknown packaging: mule-application @ line 11, column 13
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/PluginManagerException
Cleaning up file based variables
00:00
ERROR: Job failed: exit status 1

/////////////////////////////////////////////////////////////////////////////////////////////////////
and my POM.xml file is as follows

<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

	<modelVersion>4.0.0</modelVersion>

	<groupId>3f60c974-c1ba-49b4-8fd4-c66cb8afce0d</groupId>
	<artifactId>e-distributor</artifactId>
	<version>1.0.0</version>
	<packaging>mule-application</packaging>

	<name>e-distributor</name>

	<properties>
		<api.version>1.0.0</api.version>
		<api.http.port>8081</api.http.port>
		<api.https.port>8082</api.https.port>
		<api.businessGroup>APIS</api.businessGroup>

		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>

		<app.runtime>4.2.2</app.runtime>
		<anypoint.monitoring.suffix/>
		<maven-deploy-plugin.version>2.8.2</maven-deploy-plugin.version>
		<mule.maven.plugin.version>3.3.2</mule.maven.plugin.version>

		<cps.projectName>${project.artifactId}</cps.projectName>
		<cps.branchName>base</cps.branchName>
		<cps.instanceId>${instance.id}</cps.instanceId>
		<cps.keyId>base</cps.keyId>
	</properties>

	<build>
		<resources>
			<resource>
				<directory>src/main/resources-filtered/</directory>
				<filtering>true</filtering>
			</resource>
			<resource>
				<directory>src/main/resources/</directory>
				<filtering>false</filtering>
			</resource>
		</resources>
		<plugins>
			<plugin>
				<groupId>org.mule.tools.maven</groupId>
				<artifactId>mule-maven-plugin</artifactId>
				<version>${mule.maven.plugin.version}</version>
				<extensions>true</extensions>
				<configuration>
					<classifier>mule-application</classifier>
					<sharedLibraries>
					</sharedLibraries>
				</configuration>
			</plugin>
		</plugins>
	</build>

	<dependencies>
		<dependency>
			<groupId>3f60c974-c1ba-49b4-8fd4-c66cb8afce0d</groupId>
			<artifactId>cps-connector</artifactId>
			<version>1.0.6</version>
			<classifier>mule-plugin</classifier>
		</dependency>
		<dependency>
			<groupId>3f60c974-c1ba-49b4-8fd4-c66cb8afce0d</groupId>
			<artifactId>json-logger</artifactId>
			<version>1.0.2</version>
			<classifier>mule-plugin</classifier>
		</dependency>
		<dependency>
			<groupId>3f60c974-c1ba-49b4-8fd4-c66cb8afce0d</groupId>
			<artifactId>mule4-eframework2</artifactId>
			<classifier>mule-plugin</classifier>
			<version>2.0.0</version>
		</dependency>
		<dependency>
			<groupId>3f60c974-c1ba-49b4-8fd4-c66cb8afce0d</groupId>
			<artifactId>minimal-logging</artifactId>
			<version>1.0.4</version>
			<classifier>mule-plugin</classifier>
		</dependency>
		<dependency>
			<groupId>org.mule.modules</groupId>
			<artifactId>mule-apikit-module</artifactId>
			<version>1.3.6</version>
			<classifier>mule-plugin</classifier>
		</dependency>
		<dependency>
			<groupId>org.mule.connectors</groupId>
			<artifactId>mule-http-connector</artifactId>
			<version>1.5.6</version>
			<classifier>mule-plugin</classifier>
		</dependency>
	</dependencies>

	<profiles>
		
		<profile>
			<id>config-api</id>
			<build>
				<plugins>
					<plugin>
						<groupId>org.codehaus.mojo</groupId>
						<artifactId>exec-maven-plugin</artifactId>
						<version>1.6.0</version>
						<executions>
							<execution>
								<id>Development</id>
								<phase>process-resources</phase>
								<goals>
									<goal>java</goal>
								</goals>
								<configuration>
									<includePluginDependencies>true</includePluginDependencies>
									<includeProjectDependencies>false</includeProjectDependencies>
									<mainClass>com.mulesoft.java.ApiConfigTool</mainClass>
									<arguments>
										<argument>mule4ConfigureProjectResourceFile</argument>
										<argument>${u}</argument>
										<argument>${p}</argument>
										<argument>${api.businessGroup}</argument>
										<argument>${project.artifactId}</argument>
										<argument>${api.version}</argument>
										<argument>Development</argument>
									</arguments>
								</configuration>
							</execution>
							<execution>
								<id>Test</id>
								<phase>process-resources</phase>
								<goals>
									<goal>java</goal>
								</goals>
								<configuration>
									<includePluginDependencies>true</includePluginDependencies>
									<includeProjectDependencies>false</includeProjectDependencies>
									<mainClass>com.mulesoft.java.ApiConfigTool</mainClass>
									<arguments>
										<argument>mule4ConfigureProjectResourceFile</argument>
										<argument>${u}</argument>
										<argument>${p}</argument>
										<argument>${api.businessGroup}</argument>
										<argument>${project.artifactId}</argument>
										<argument>${api.version}</argument>
										<argument>Test</argument>
									</arguments>
								</configuration>
							</execution>
							<execution>
								<id>Production</id>
								<phase>process-resources</phase>
								<goals>
									<goal>java</goal>
								</goals>
								<configuration>
									<includePluginDependencies>true</includePluginDependencies>
									<includeProjectDependencies>false</includeProjectDependencies>
									<mainClass>com.mulesoft.java.ApiConfigTool</mainClass>
									<arguments>
										<argument>mule4ConfigureProjectResourceFile</argument>
										<argument>${u}</argument>
										<argument>${p}</argument>
										<argument>${api.businessGroup}</argument>
										<argument>${project.artifactId}</argument>
										<argument>${api.version}</argument>
										<argument>Production</argument>
										<argument>mule4-client-credentials-policy</argument>
										<argument>empty-client-access-list</argument>
										<argument>manual-approval-required</argument>
									</arguments>
								</configuration>
							</execution>
						</executions>
						<dependencies>
							<dependency>
								<groupId>3f60c974-c1ba-49b4-8fd4-c66cb8afce0d</groupId>
								<artifactId>mule-api-config</artifactId>
								<version>1.0.8</version>
								<type>jar</type>
							</dependency>
						</dependencies>
					</plugin>
				</plugins>
			</build>
		</profile>

		
		
		<profile>
			<id>anypoint_monitoring</id>
			<properties>
				<anypoint.monitoring.suffix>-AM</anypoint.monitoring.suffix>
			</properties>
		</profile>

		
		<profile>
			<id>public-lb</id>
			<properties>
				<api.http.port>8081</api.http.port>
				<api.https.port>8082</api.https.port>
			</properties>
		</profile>
		<profile>
			<id>dlb</id>
			<properties>
				<api.http.port>8091</api.http.port>
				<api.https.port>8092</api.https.port>
			</properties>
		</profile>

		
		<profile>
			<id>cloudhub</id>
			<build>
				<plugins>
					<plugin>
						<groupId>org.mule.tools.maven</groupId>
						<artifactId>mule-maven-plugin</artifactId>
						<version>${mule.maven.plugin.version}</version>
						<extensions>true</extensions>
						<configuration>
							<classifier>mule-application</classifier>
							<cloudHubDeployment>
								<uri>https://anypoint.mulesoft.com</uri>
								<muleVersion>${app.runtime}${anypoint.monitoring.suffix}</muleVersion>
								<username>${u}</username>
								<password>${p}</password>
								<applicationName>${cloudhub.name}</applicationName>
								<artifact>${mule.artifact}</artifact>
								<businessGroup>${deploy.businessGroup}</businessGroup>
								<environment>${deploy.environment}</environment>
								<workers>${ch.workers}</workers>
								<workerType>${ch.workerType}</workerType>
								<deploymentTimeout>${ch.deploymentTimeout}</deploymentTimeout>
								<region>${ch.region}</region>
								<properties>
									<mule.env>${deploy.environment}</mule.env>
									<configuration_property_service_api.name/>
									<configuration_property_service_api.version/>
									<anypoint.platform.client_id>${ap_id}</anypoint.platform.client_id>
									<anypoint.platform.client_secret>${ap_secret}</anypoint.platform.client_secret>
									<mule.server>${cloudhub.name}${cloudhub.domain}</mule.server>
									<host.name>${cloudhub.name}${cloudhub.domain}</host.name>
									<anypoint.platform.visualizer.layer>Experience</anypoint.platform.visualizer.layer>
									<cps.configServerBaseUrl>${cps.configServerBaseUrl}</cps.configServerBaseUrl>
									<cps.insecure>${cps.insecure}</cps.insecure>
									<cps.projectName>${cps.projectName}</cps.projectName>
									<cps.branchName>${cps.branchName}</cps.branchName>
									<cps.instanceId>${cps.instanceId}</cps.instanceId>
									<cps.keyId>${cps.keyId}</cps.keyId>
									<cps.clientId>${cps.clientId}</cps.clientId>
									<cps.clientSecret>${cps.clientSecret}</cps.clientSecret>
									<mule_cps_keystore_filename>${mule_cps_keystore_filename}</mule_cps_keystore_filename>
									<mule_cps_keystore_password>${mule_cps_keystore_password}</mule_cps_keystore_password>
									<mule_cps_key_password>${mule_cps_key_password}</mule_cps_key_password>
									<mule_cps_keystore_client_id>${mule_cps_keystore_client_id}</mule_cps_keystore_client_id>
									<mule_cps_keystore_client_secret>${mule_cps_keystore_client_secret}</mule_cps_keystore_client_secret>
									<mule.cps.retry.count>${mule.cps.retry.count}</mule.cps.retry.count>
									<api.http.port>${api.http.port}</api.http.port>
									<api.https.port>${api.https.port}</api.https.port>
									<api.base>${api.base}</api.base>
									<api.version>${api.version}</api.version>
									<project.version>${project.version}</project.version>
									<my.client_secret>${my.client_secret}</my.client_secret>
									<sun.net.http.allowRestrictedHeaders>false</sun.net.http.allowRestrictedHeaders>
									<anypoint.platform.config.analytics.agent.enabled>true</anypoint.platform.config.analytics.agent.enabled>
								</properties>
							</cloudHubDeployment>
						</configuration>
					</plugin>
				</plugins>
			</build>
		</profile>
		<profile>
			<id>rtf</id>
			<build>
				<plugins>
					<plugin>
						<groupId>org.mule.tools.maven</groupId>
						<artifactId>mule-maven-plugin</artifactId>
						<version>${mule.maven.plugin.version}</version>
						<extensions>true</extensions>
						<configuration>
							<classifier>mule-application</classifier>
							<runtimeFabricDeployment>
								<uri>https://anypoint.mulesoft.com</uri>
								<provider>MC</provider>
								<username>${u}</username>
								<password>${p}</password>
								<environment>${deploy.environment}</environment>
								<target>${deploy.rtf-target}</target>
								<muleVersion>${app.runtime}${anypoint.monitoring.suffix}</muleVersion>
								<applicationName>${rtf.name}</applicationName>
								<skipDeploymentVerification>true</skipDeploymentVerification>
								<deploymentSettings>
									<cpuReserved>${rtf.cpuReserved}</cpuReserved>
									<memoryReserved>${rtf.memoryReserved}</memoryReserved>
									<publicUrl>${rtf.domain}/${rtf.name}</publicUrl>
									<replicationFactor>${rtf.instances}</replicationFactor>
									<lastMileSecurity>true</lastMileSecurity>
								</deploymentSettings>
								<properties>
									<mule.env>${deploy.environment}</mule.env>
									<anypoint.platform.client_id>${ap_id}</anypoint.platform.client_id>
									<anypoint.platform.client_secret>${ap_secret}</anypoint.platform.client_secret>
									<mule.server>${deploy.target}</mule.server>
									<host.name/>
									<cps.configServerBaseUrl>${cps.configServerBaseUrl}</cps.configServerBaseUrl>
									<cps.insecure>${cps.insecure}</cps.insecure>
									<cps.projectName>${cps.projectName}</cps.projectName>
									<cps.branchName>${cps.branchName}</cps.branchName>
									<cps.instanceId>${cps.instanceId}</cps.instanceId>
									<cps.keyId>${cps.keyId}</cps.keyId>
									<cps.clientId>${cps.clientId}</cps.clientId>
									<cps.clientSecret>${cps.clientSecret}</cps.clientSecret>
									<mule_cps_keystore_filename>${mule_cps_keystore_filename}</mule_cps_keystore_filename>
									<mule_cps_keystore_password>${mule_cps_keystore_password}</mule_cps_keystore_password>
									<mule_cps_key_password>${mule_cps_key_password}</mule_cps_key_password>
									<mule_cps_keystore_client_id>${mule_cps_keystore_client_id}</mule_cps_keystore_client_id>
									<mule_cps_keystore_client_secret>${mule_cps_keystore_client_secret}</mule_cps_keystore_client_secret>
									<mule.cps.retry.count>${mule.cps.retry.count}</mule.cps.retry.count>
									<anypoint.platform.visualizer.layer>Experience</anypoint.platform.visualizer.layer>
									<http.port>8081</http.port>
									<https.port>8081</https.port>
									<api.http.port>8081</api.http.port>
									<api.https.port>8081</api.https.port>
									<api.base>${api.base}</api.base>
									<api.version>${api.version}</api.version>
									<project.version>${project.version}</project.version>
									<my.client_secret>${my.client_secret}</my.client_secret>
									<sun.net.http.allowRestrictedHeaders>false</sun.net.http.allowRestrictedHeaders>
									<anypoint.platform.config.analytics.agent.enabled>true</anypoint.platform.config.analytics.agent.enabled>
								</properties>
							</runtimeFabricDeployment>
						</configuration>
					</plugin>
				</plugins>
			</build>
		</profile>

		<profile>
			<id>hybrid</id>
			<build>
				<plugins>
					<plugin>
						<groupId>org.mule.tools.maven</groupId>
						<artifactId>mule-maven-plugin</artifactId>
						<version>${mule.maven.plugin.version}</version>
						<extensions>true</extensions>
						<configuration>
							<classifier>mule-application</classifier>
							<armDeployment>
								<uri>https://anypoint.mulesoft.com</uri>
								<username>${u}</username>
								<password>${p}</password>
								<target>${deploy.target}</target>
								<targetType>${deploy.targetType}</targetType>
								<environment>${deploy.environment}</environment>
								<muleVersion>${app.runtime}</muleVersion>
								<businessGroup>${deploy.businessGroup}</businessGroup>
								<applicationName>${hybrid.name}</applicationName>
								<properties>
									<api.version>${api.version}</api.version>
									<project.version>${project.version}</project.version>
								</properties>
							</armDeployment>
						</configuration>
					</plugin>
				</plugins>
			</build>
		</profile>

		<profile>
			<id>artifact-repo</id>
			<distributionManagement>
				<repository>
					<id>corporate-artifact-repository</id>
					<name>Corporate Artifact Repository</name>
					<url>${corporate-artifact-repository-url}</url>
					<layout>default</layout>
				</repository>
			</distributionManagement>
		</profile>

		<profile>
			<id>code-check</id>
			<build>
				<plugins>
					<plugin>
						<groupId>org.codehaus.mojo</groupId>
						<artifactId>exec-maven-plugin</artifactId>
						<version>1.6.0</version>
						<executions>
							<execution>
								<id>CodeCheck</id>
								<phase>process-sources</phase>
								<goals>
									<goal>java</goal>
								</goals>
								<configuration>
									<includePluginDependencies>true</includePluginDependencies>
									<includeProjectDependencies>false</includeProjectDependencies>
									<mainClass>com.mulesoft.services.mulecodechecker.MuleCodeChecker</mainClass>
									<arguments>
									</arguments>
								</configuration>
							</execution>
						</executions>
                                                <dependencies>
                                                        <dependency>
                                                               <groupId>3f60c974-c1ba-49b4-8fd4-c66cb8afce0d</groupId>
                                                               <artifactId>muleCodeChecker</artifactId>
                                                               <version>1.0.0</version>
                                                               <type>jar</type>
                                                       </dependency>
                                                </dependencies>
					</plugin>
				</plugins>
			</build>
		</profile>

		<profile>
			<id>exchange</id>
			<build>
				<plugins>
					<plugin>
						<groupId>org.codehaus.mojo</groupId>
						<artifactId>exec-maven-plugin</artifactId>
						<version>1.6.0</version>
						<executions>
							<execution>
								<id>Clean-Exchange-RTF</id>
								<phase>clean</phase>
								<goals>
									<goal>java</goal>
								</goals>
								<configuration>
									<includePluginDependencies>true</includePluginDependencies>
									<includeProjectDependencies>false</includeProjectDependencies>
									<mainClass>com.mulesoft.java.APExchangeClean</mainClass>
									<arguments>
										<argument>clean</argument>
										<argument>${u}</argument>
										<argument>${p}</argument>
										<argument>3f60c974-c1ba-49b4-8fd4-c66cb8afce0d</argument>
										<argument>${project.artifactId}</argument>
										<argument>1.0.0</argument>
									</arguments>
								</configuration>
							</execution>
						</executions>
                                                <dependencies>
                                                        <dependency>
                                                               <groupId>3f60c974-c1ba-49b4-8fd4-c66cb8afce0d</groupId>
                                                               <artifactId>ap-exchange-clean</artifactId>
                                                               <version>1.0.0</version>
                                                               <type>jar</type>
                                                       </dependency>
                                                </dependencies>
 					</plugin>
				</plugins>
			</build>
			<distributionManagement>
				<repository>
					<id>my-organization-exchange-repository</id>
					<name>My Organization Exchange</name>
					<url>https://maven.anypoint.mulesoft.com/api/v2/organizations/3f60c974-c1ba-49b4-8fd4-c66cb8afce0d/maven</url>
					<layout>default</layout>
				</repository>
			</distributionManagement>
		</profile>
	</profiles>
</project>

**Comment by gallandarakhneorg** [comment]
This issue is not related to the SARL project.
