### ISSUE TITLE
Problem with `it` in English Auction

### ISSUE THREAD

**Issue by ssardina** [sarl/sarl#1067]
**Describe the bug**

The use of `it.ID` gives error:

![image](https://user-images.githubusercontent.com/2368384/111540198-f17f7780-87c2-11eb-9e41-0c2d38b717b8.png)

But it works well when `this.ID` is used. 

This comes from the [English Auction tutorial](http://www.sarl.io/docs/official/tutorials/HolonicAuction.html):

![image](https://user-images.githubusercontent.com/2368384/111540307-1bd13500-87c3-11eb-92bf-bbbc870ebb2a.png)

**Expected behavior**

No errors?

**System configuration:**
-- SARL version:	0.11.0
-- SARL compiler:	0.11.0
-  - [] Eclipse compiler without Maven	
-  - [X ] Eclipse compiler with Maven	
-  - [ ] Maven compiler on the command line	
-  - [ ] sarlc compiler	
-- Java JDK version (with the manufacturer name):	
-- Operating System:	
-  - [x] Linux 64bits	
-  - [ ] Windows 64bits	
-  - [ ] MacOS 64bits

**Comment by gallandarakhneorg** [comment]
To confirm my expectation, are you using version `0.11`?

**Comment by ssardina** [comment]
Yes! Sorry.

**Comment by gallandarakhneorg** [comment]
If yes, the API is a little incosistent. Indeed, `it` represents the local argument of the lambda expression that is of type `Address`, and `this` is of type `Agent`.

In version 0.11, the API of `Address` provides the function `getUUID` for obtainiing the identifier of the agent represented by the address.
And the API of `Agent` provides the function `getID` for obtaining the identifier of the current agent.

In version 0.12 (release planned during the coming 2 months), the API is unified and `getUUID` is replaced by `getID` (with a deprecation of the old function).

**Comment by gallandarakhneorg** [comment]
Quick fix: replace `it.ID` by `it.UUID`

**Comment by gallandarakhneorg** [comment]
Please note also that the meanings of `it.UUID` and `this.ID` are not exactly the same. The first replies the identifier of the agent represented by the address, i.e. a possible candidate for receiving the event in the context of the lambda usage; and `this.ID` replies the identifier of the current agent, i.e. the emitter of the event.

**Comment by gallandarakhneorg** [comment]
The online document may already exhibits code that is compatible with version  `0.12` because of the generation pipeline (this is an issue I have to solve for the next versions).

**Comment by ssardina** [comment]
Thanks a lot. So the doc is aligned with 0.12.0, all good!

**Comment by gallandarakhneorg** [comment]
Yes. The version of SARL that is concerned by the documentation is mentionned at the end of each page.
Nevertheless, your report indicates that we must change the way we are publishing the documentation in order to be consistentt.

**Comment by ssardina** [comment]
I see:
![image](https://user-images.githubusercontent.com/2368384/111594052-b0b54c00-881e-11eb-9cc3-fad60ae29b43.png)

But don't worry, don't think it is a big issue. I guess the "best" would be to keep the doc of the old version frozen?
-----------

Thanks again. I think the English Auction Tutorial  would benefit from elaboration to explain what that line of emitting within the scope is. Here is what I wrote:

https://gist.github.com/ssardina/ba59838bd6f2c2a64896e79533f35054#emit-an-event-with-a-scope

It is a perfect place to explain emitting in a scope using that notation, and referring to [the doc on that](https://gist.github.com/ssardina/ba59838bd6f2c2a64896e79533f35054#emit-an-event-with-a-scope), explaining the `it`, and the fact that agent.ID = agent's inner context ID

Those tutorials are are perfect place to explain everything and put pointers to the doc places, which are sometimes hard to find...

Thanks again @gallandarakhneorg , very useful and quick!
