### ISSUE TITLE
Set verbose level for SRE gives error - Document proper dependencies in Maven projects

### ISSUE THREAD

**Issue by ssardina** [sarl/sarl#1080]
**Description of your issue:**

![image](https://user-images.githubusercontent.com/2368384/123222944-c8822780-d513-11eb-858b-abf72101c694.png)

I am using SARL 0.11.0 and the class `BootMAS` has this:

![image](https://user-images.githubusercontent.com/2368384/123223023-dfc11500-d513-11eb-9695-0e928c1bdac8.png)

**Comment by ssardina** [comment]
In fact, I used to have this line which worked well:

```java
		sre.verboseLevel = 7
```

**Comment by gallandarakhneorg** [comment]
Dear @ssardina . Could you provide the dependencies' list from your `pom.xml` file?

**Comment by ssardina** [comment]
Of course, sorry, here is the full pom file.

[pom.xml.txt](https://github.com/sarl/sarl/files/6708355/pom.xml.txt)

**Comment by ssardina** [comment]
And if I comment that line about verbose setting:

![image](https://user-images.githubusercontent.com/2368384/123247851-a051f300-d52a-11eb-8bc4-84f22dcd1344.png)

**Comment by gallandarakhneorg** [comment]
Please add the following dependency into your pom file, to be sure that you are using the SRE at run-time:
```
<dependency>
          <groupId>io.janusproject</groupId>
          <artifactId>io.janusproject.kernel</artifactId>
          <version>3.${sarl.version}</version>
</dependency>
```

Anyway, I just realize that this need of dependency is not explained in the SARL documentation.

**Comment by ssardina** [comment]
Ohhh you know I always had that dependency, and I thought I did not need it anymore with the new SRE!! I am so....

**Comment by ssardina** [comment]
I even deleted that part today when I saw this:

http://www.sarl.io/docs/official/tools/MavenSarlPlugin.html

**Comment by ssardina** [comment]
But you are totally right, one thing is the SARL compiler, another is the runtime

**Comment by ssardina** [comment]
Sorry didn't realized you left it for the doc. Good idea.

**Comment by gallandarakhneorg** [comment]
No problem :-)
I have to update all the pages in the documentation in order to make very clear the dependency for compilation and those for running.
You issue will remind us to do so :-)

**Comment by gallandarakhneorg** [comment]
Two actions are ongoing for solving this issue:

* The documentation is updated to be sure that the dependency tree is clear.
* The `maven-sarl-plugin` determines if a SRE is in the class path of the project. If there is no SRE in the classpath, a warning is printed out to notify that the SARL program cannot be run outside a SRE, e.g. , by usig the `janus` command line tool.

**Comment by gallandarakhneorg** [comment]
This issue is also related to Issue #1077.
