### ISSUE TITLE
Compilation failure

### ISSUE THREAD

**Issue by axel7083** [sarl/sarl#1087]
Following the details in [CONTRIBUTING.adoc](https://github.com/sarl/sarl/blob/master/CONTRIBUTING.adoc) I tried to compile using the `mvn clean install -Dmaven.test.skip=true -Dcheckstyle.skip=true` command the master branch (last tested https://github.com/sarl/sarl/commit/9af132e078d6be1aa0226edf3b81bed868298801).

As a result I obtained the error message
 ```
...
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project
 io.sarl.maven.batchcompiler: Compilation failure
[ERROR] /sarl/sarl/main/internalmaven/io.sarl.maven.batchcompiler/src/main/java/io/sarl/lang/compiler/batch/CancelIndicatorProgressMonitor.java:[24,32] cannot access org.eclipse.core.runtime.IProgressMonitor
[ERROR]   bad class file: /root/.m2/repository/org/eclipse/platform/org.eclipse.equinox.common/3.15.100/org.eclipse.equinox.common-3.15.100.jar(org/eclipse/core/runtime/IProgressMonitor.class)
[ERROR]     class file has wrong version 55.0, should be 52.0
[ERROR]     Please remove or make sure it appears in the correct subdirectory of the classpath.
[ERROR]
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

### Configuration
The config used are similar to the one provided.
```
Java version: 1.8.0_282, vendor: Oracle Corporation, runtime: /usr/local/openjdk-8/jre
Default locale: en, platform encoding: UTF-8
OS name: "linux", version: "5.10.60.1-microsoft-standard-wsl2", arch: "amd64", family: "unix"
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /usr/share/maven
```

The issue is reproducable, I created a Dockerfile based on the Maven official docker image.

### Dockerfile
```Dockerfile
FROM maven:3.6-jdk-8
RUN java -version
RUN mvn -version
RUN git clone https://github.com/sarl/sarl --depth=1
WORKDIR /sarl
RUN mvn clean install -Dmaven.test.skip=true -Dcheckstyle.skip=true
```

Simply run `docker build -f ./Dockerfile .`

**Comment by gallandarakhneorg** [comment]
The Maven's Tycho plugin is downloading a recent Eclipse mdule, even if we have specified an older version. This version contains a module that is compiled with Java 11. It cannot be loaded by a Java 8 virtual machine.

You could move to the `0.13-java11` branch for obtaining a version of SARL was is adapted to Java 11.

**Comment by gallandarakhneorg** [comment]
Branch `0.13-java11` is now deprecated and replaced by branch `0.13-java17`.
The compilation process has changed a lot. I propose to close this issue when the new branch is merge into the master branch.
