### ISSUE TITLE
Link to demos are not working from the website

### ISSUE THREAD

**Issue by Gcurrivand** [sarl/sarl#1125]
On sarl.io some links to the github redirect to an 404.

For example on the firework demo
![image](https://github.com/sarl/sarl/assets/114084438/dbad1d36-dce2-4ed9-980f-470dbc728871)

![image](https://github.com/sarl/sarl/assets/114084438/b6956c00-ea0e-4219-a05d-6028d1869323)

**Comment by gallandarakhneorg** [comment]
Thank you. The URLs have been fixed. You have to refresh the pages in your browser to see the fixed URL.
