### ISSUE TITLE
Damaged product for macOS

### ISSUE THREAD

**Issue by gallandarakhneorg** [sarl/sarl#1129]

**Comment by gallandarakhneorg** [comment]
Working configuration:

* Java Oracle 17.0.8, manually installed
* macOS 10.13

**Comment by srodriguez** [comment]
Quick update. 
Downloading the file using Firefox and Safari reports the file as "damaged".
However, when using "wget" it works find. 
I'll keep working on it.

**Comment by gallandarakhneorg** [comment]
I have downloaded the Intel macOS product from the SARL website with Chromium (on Linux box). I did not see any different with my previous message. SARL is starting correctly.

**Comment by gallandarakhneorg** [comment]
Close for same Issue #1152.
