### ISSUE TITLE
Create a CLI compiler

### ISSUE THREAD

**Issue by gallandarakhneorg** [sarl/sarl#149]
In addition to the Maven plugin for SARL, it may be useful to provide a command-line compiler.

The [Xtext FAQ](https://wiki.eclipse.org/Xtext/FAQ) provides a starting point for invoking SARL compiler from a Java application.

**Comment by srodriguez** [comment]
Even think about janus run cli.

**Comment by gallandarakhneorg** [comment]
See #439 for the CLI interface of Janus.

**Comment by gallandarakhneorg** [comment]
The CLI tool is generated for Windows, Linux and OSX platforms.
Now, we need to decide where these tools are available (on the website, in the Eclipse product, etc.)

**Comment by ssardina** [comment]
That is great, so I assume this will be a command that one can run directly on command line and uses only Java (no Maven); is this correct?

If it is simple, then maybe is part of documentation, but I am guessing it is quite involved "script", so maybe making it available in the web page is enough? (and the git distro)

**Comment by gallandarakhneorg** [comment]
You're right. These tools are standard scripts that are launching the Java VM with the SARL compiler jar file. They provides a command line interface that is following the CLI standards (mostly from Posix/GNU). You don't need to have Maven for using these tools because they are standard Java applications.

I fully agree to add the download links on the "Download" webpage of sarl.io.

I propose to include the files into the SARL Eclipse product folder too, in order to have the SARL editor and the SARL CLI compiler in the same folder.
