### ISSUE TITLE
Where putting Jaak back?

### ISSUE THREAD

**Issue by gallandarakhneorg** [sarl/sarl#182]
Jaak is a grid-based situated environment provided on the Janus platform v1.

Since the implementation of Jaak becomes almost independent from Janus, do we create a repository in the SARL team, in the Janus team, or somewhere different.

This question is related to our policy for supporting SDK extensions and language extensions.

**Comment by srodriguez** [comment]
@gallandarakhneorg Great job!!!

How about moving it as a top level repo inside SARL (sarl/jaak)?

**Comment by gallandarakhneorg** [comment]
Delaying the decision until Jaak is marked as stable for its SARL-based version and the expected Eclipse panels are developed.
