### ISSUE TITLE
Behavior.getSkill not compatible with inheritance

### ISSUE THREAD

**Issue by cboittin** [sarl/sarl#210]
I have a capacity that inherits another one, and a skill that implements the child one.
My agent uses the child capacity and its associated skill.

If I define a behavior which uses getSkill for the child capacity, it works fine. However, using getSkill on the parent capacity returns null, which is odd since the skill also implements it.

Wouldn't it be more logical and improve code reusability to allow the Behavior.getSkill method to work with capacity inheritance ?

Here is a sample code that shows the "error".

```java
import io.sarl.core.Behaviors
import io.sarl.core.Initialize
import io.sarl.core.DefaultContextInteractions
import io.sarl.core.Schedules

/**
 * Capacities and Skill
 */
capacity ParentCap {
    def update
}
capacity ChildCap extends ParentCap {
    def anyFunction
}
skill ChildCapSkill implements ChildCap {
    def update {
        println("updated")
    }
    def anyFunction {
        // TODO: Auto-generated action.
    }
}

/**
 * Behavior
 */
event TestEvent
behavior TestInheritanceBehavior {
    on TestEvent {
        var sk = getSkill(ParentCap)
        sk.update
    }
}

/**
 * Agent
 */
agent TestInheritanceAgent {
    uses ChildCap, Behaviors
    on Initialize {
        this.setSkill(ChildCap, new ChildCapSkill)
        this.registerBehavior(new TestInheritanceBehavior(this))
    }
}

/**
 * Boot Agent
 */
agent BootAgent {
    uses DefaultContextInteractions, Schedules
    on Initialize {
        this.spawn(TestInheritanceAgent)
        this.update
    }
    def update() {
        every(1000) [
            println("Sending event")
            this.emit(new TestEvent)
        ]
    }
}
```

**Comment by gallandarakhneorg** [comment]
The documentation of `setSkill` and `getSkill` must be updated for making clear that the capacities in arguments must be the one to set/retreive (not the super capacities).

**Comment by srodriguez** [comment]
The discussion here turns around explicit capacity setting vs implicit capacity settings.

I lean towards explicit capacity setting and  We could change the signature of setSkill 
```
protected <S extends Skill> S setSkill( S skill, Class<? extends Capacity> capacity ... )
``` 

This way we can set the agent's capacities like this

```
setSkill(new ChildCapSkill, ParentCap, ChildCap)
```

What do you think?

**Comment by gallandarakhneorg** [comment]
I agree.
