### ISSUE TITLE
Ctrl+Click not functionning properly in SARL in eclipse

### ISSUE THREAD

**Issue by cboittin** [sarl/sarl#241]
In eclipse, Ctrl+Click is useful to quickly get to the definition of a class, function or field.
With SARL files, it isn't fully functionnal.
It is possible to get to the definition of a function or field, but the default is reversed : Ctrl+Click opens up a menu with "Open Return type" as first entry (which is far less useful), and the desired "Open Implementation" as second entry.
Also it is impossible to open a class definition in this way from a .sarl file.

.java files work fine, though.

**Comment by gallandarakhneorg** [comment]
Seems to work with 0.4:
* Ctrl+click on a feature in the same file will open the popup with "open declaration/open implementation" and go to the feature.
* Ctrl+click on a feature in another file will open the standard Java popup and go to the feature.
