### ISSUE TITLE
Add a tutorial for creating a SRE for the tinyMAS platform.

### ISSUE THREAD

**Issue by gallandarakhneorg** [sarl/sarl#284]
A SARL Runtime Environment (SRE) could be defined based on a specific platform.
The documentation section of the SARL language may contain a tutorial for creation a SRE.

The tutorial may take Janus and TinyMAS as examples.

The key points of the tutorial are:
- the implementation of the SARL core API
- the enhancement of the Manifest of the platform's jar file.

**Comment by gallandarakhneorg** [comment]
Code is available on: https://github.com/gallandarakhneorg/tinymas

**Comment by scenaristeur** [comment]
Bonjour, 
Comment lancer des agents SARL depuis Processing https://processing.org ? J'avais à lancer des agents Janus avant que vous ne basculiez sur SARL, mais Processing ne prenant pas en compte Xtext, j'avais été bloqué. Croyez vous que cela soit possible ? 
Merci

**Comment by gallandarakhneorg** [comment]
Bonjour.
Il n'y a aucune raison de ne pas pouvoir lancer avec processing un agent Janus v2.x (généralement généré à partir de code SARL) si vous pouviez le faire avec un agent Janus v1.x.

Toutefois, l'API de Janus a fortement évolué entre sa version 1.x et sa version 2.x. Les méthodes de lancement à partir d'un programme Java tier ont évolué. De plus, le code d'un agent qui fonctionnait sur la version 1.x de Janus n'est plus compatible avec la version 2.x de Janus. L'API a également fortement évoluée vers plus de simplicité.

Je pense que la meilleure manière de lié Processings et Janus v2 est d'utiliser la méthode de lancement d'agents avec du code Java.
La documentation pouvant servir de point de départ est située à l'adresse : http://www.sarl.io/docs/suite/io/sarl/docs/gettingstarted/RunSARLAgentFromAJavaProgramSpec.html 

La syntaxe utilisée dans cette documentation est la syntaxe SARL, mais elle peut être facilement transcrite en Java. Par exemple, pour lancer deux agents :
```java
import io.janusproject.Boot;
import io.janusproject.kernel.Kernel;
import myprogram.MyAgent;
// MyAgent est un type Java issu de la compilation d'un code d'agent SARL,
// ou de l'écriture manuelle du code Java en respectant la nouvelle API.
class X {
    public void main(String[] args) {
        // Lancement du premier agent
        Kernel janusKernel = Boot.startJanus(null, MyAgent.class);
        // Lancement d'autres agents
       janusKernel.spawn(MyAgent.class);
    }
}
```

Je recommande également fortement pour intégrer la bibliothèque Janus dans votre projet, soit d'utiliser Maven, soit d'utiliser le fichier Jar avec Janus et toutes ses dépendances, qui peut être téléchargé sur http://www.janusproject.io

**Comment by gallandarakhneorg** [comment]
The tutorial is available at: http://www.sarl.io/docs/suite/io/sarl/docs/tutorials/CreatingASARLRunTimeEnvironmentForTheTinyMASPlatformSpec.html

@ngaud, @srodriguez, please read and update its content for making it easier to read and understand.

**Comment by scenaristeur** [comment]
merci pour ces infos. Un peu trop occupé d'ici la fin du mois, je retesterais en septembre  ;-)

**Comment by gallandarakhneorg** [comment]
Si vous avez un repository Git en accès libre, je pourrais y jeter un coup d’œil.
