### ISSUE TITLE
Include Janus in the SARL product

### ISSUE THREAD

**Issue by gallandarakhneorg** [sarl/sarl#303]
When not using Maven-based SARL project (during student practice sessions for example), the runtime environment must be download by hand.

It will be helpful to have Janus installed in the product as an Eclipse plugin, or downloaded on the fly by an Eclipse plugin.

**Comment by ngaud** [comment]
It will be done as the same time as the integration of SARL demos (see #314) in a single product managed by oomph (see #346). The project will be split in four different parts:
- the SARL language and its sets of plug-ins.
- the Janus encapsulated into an eclipse plug-ins and its corresponding UI.
- the SARL demos integrated as eclipse plug-ins with a direct access from the welcome page
- and the real SARL product merging all contributions into a single eclipse applications

**Comment by ngaud** [comment]
During this refactoring of Janus, the problem of the injection engine: Google Guice vs Eclipse Part-4:Dependency injection. 
As well as the strategy to define Janus plug-ins: a single big plug-in or a collection of interrelated small plugins.

**Comment by gallandarakhneorg** [comment]
The structure of the project may be:
```
root
|-- build-tools (including checkstyle, scripts, licences)
|-- sarl (the current SARL tools, except those in build-tools and the update-site module)
|-- maven (the current maven module)
|-- janus (the current version of Janus)
|-- product (the old update-site module, and a plugin/feature for janus)
|-- latex (the current latex folder)
|-- docs (the documentation)
```

**Comment by ngaud** [comment]
root
|-- build-tools (including checkstyle, scripts, licences)
|-- sarl (the current SARL tools, except those in build-tools and the update-site module)
|-- maven (the current maven module)
|-- janus (the current version of Janus)
|-- sarl-product (the old update-site module, and a plugin/feature for janus)
    |-- oomph setup / product
    |-- old update-site
    |-- external contributions plugins
           |-- Janus default SRE plugin
|-- latex (the current latex folder)
|-- docs (the documentation)
|-- dev-tools
      |-- oomph for developers

**Comment by gallandarakhneorg** [comment]
Since Jnario is still dependent on old Xtext library, a specific oomph for documentation contributors may be needed.
```
root
|-- build-tools (including checkstyle, scripts, licences)
|-- sarl (the current SARL tools, except those in build-tools and the update-site module)
|-- maven (the current maven module)
|-- janus (the current version of Janus)
|-- sarl-product (the old update-site module, and a plugin/feature for janus)
    |-- oomph setup / product
    |-- old update-site
    |-- external contributions plugins
           |-- Janus default SRE plugin
|-- latex (the current latex folder)
|-- docs (the documentation)
|-- dev-tools
      |-- oomph for developers 
      |-- oomph for documentation contributors. 
```

**Comment by gallandarakhneorg** [comment]
See commit 4e9f372e0bcbf92842715e740e897a4d7e2214d7.
