### ISSUE TITLE
sarl/janus avec Processing

### ISSUE THREAD

**Issue by scenaristeur** [sarl/sarl#331]
Bonjour, j'avais fait un test il y a longtemps, avec janus1 et Processing (https://processing.org/), ça paraissait prometteur, mais là avec janus2 ou sarl, je suis un peu perdu, je ne parvient pas à lancer des agents.

J'utilisais donc Processing, en incluant "kernel1.0-withdependencies.jar"  avec le code suivant : 

```
import org.janusproject.kernel.Kernel;
import org.janusproject.kernel.status.Status;
import org.janusproject.kernel.agent.Agent;
import org.janusproject.kernel.agent.Kernels;
import org.janusproject.kernel.status.StatusFactory;

Kernel k;

BallAgent ball1= new BallAgent();
BallAgent ball2= new BallAgent();
float distance;


void setup() {
  size(displayWidth, displayHeight);
  k = Kernels.get();
  k.launchLightAgent(ball1, "ball1");
  k.launchLightAgent(ball2, "balle2");
}

void draw() {
  background(205);
  ball1.update();
  ball2.update();
  ball1.draw(); 
  ball2.draw();
  distance = dist(ball1.x, ball1.y, ball2.x, ball2.y);
  text (distance, 100, 110);
}
```
```
/////// CLASSE BALL

class BallAgent extends Agent {

  private static final long serialVersionUID = 5326548050822336187L; 

  float x=random(width)+random(100);
  float y=random(height);
  int dx;
  int dy;

  BallAgent() {
  }
  @Override
    public Status activate(Object... parameters) {   
    //Initializes capacities and memory 
    //Creates or joins groups and requests roles   
    //... 


    dx=1;
    dy=1;
    return StatusFactory.ok(this);
  } 

  public Status live() {
    // x++;
    println(this.getName()+" is alive : "+x);
    return null;
  }

  void draw() {
    fill(255, 255, 0, 10);
    rect(x, y, 10, 10);
    fill(0);
    text(this.getName(), x, y);
  }
  void update() {
    if ((x<=0)||(x> width)) {    
      dx=dx*(-1);
    }
    if ((y<= 0) ||(y> height) ) {    
      dy=dy*(-1);
    }
    x=x+dx;
    y=y+dy;
  }
}
```

et ça fonctionnait, y'a t'il moyen d'en faire autant avec janus2 ?

Merci.
David

**Comment by gallandarakhneorg** [comment]
Avec la version 2 de Janus, il est plus simple de recoder les agents avec le language SARL. En effet, le code Java sur la version 2 de Janus et équivalent à la version 1 sera assez "illisible" (les fonctions activate, live et end ont disparu au profit d'observateurs d'événements).

Le plus gros changement en passant à la version 2 de Janus sera certainement l'exécution réellement parallèle des agents. Contrairement à la version 1, il n'est plus possible de séquentialiser l'exécution des agents.

Je vais réfléchir rapidement à cet évolution et te proposer des pistes.

**Comment by gallandarakhneorg** [comment]
Ton exemple de code est incompatible avec une vision réellement orientée agent : il ne faut jamais acceder à un attribut d'un agent à partir d'un autre objet (dans ton code x, y), et il ne faut pas appeller une fonction de l'agent (update). Le language SARL ne te permettra pas de le faire. 

Dans ton problème, il y a des agents Ball qui doivent calculer leurs positions, et un agent "Application" qui contrôle l'affichage général et donne l'ordre aux autres agents de se mettre à jour.

Je défini l'événement `Update` qui correspond à cet ordre.
Je défini également l'événement `Updated` qui sera envoyé par les agents Ball pour indiquer à quelle position ils sont:
```
package monapplication
event Update
event Updated {
	val x : float
	val y : float
	new (x : float, y : float) {
		this.x = x
		this.y = y
	}
}
```

Ensuite, les agents Ball doit pouvoir s'afficher. Pour permettre une plus grande modularité et évolutivité du code, je défini la capacité `Drawer` qui sera utiliser par les agents Ball pour s'afficher. Cette capacité n'est pas liée à une bibliothèque d'affichage particulière:
```
capacity Drawer {
	// Retourne la largeur de la zone d'affichage
	def getWidth : float
	// Retourne la hauteur de la zone d'affichage
	def getHeight : float
	// Affiche l'agent Ball aux coordonnées données.
	def draw(x : float, y : float)
}
```

Afin d'utiliser la bibliothèque Processing, il est maintenant possible d'implanter une compétence (skill) proposant une implantation des fonctions de `Drawer` avec Processing:
```
skill ProcessingDrawer implements Drawer {
	def getWidth : float {
		return width
	}

	def getHeight : float {
		return height
	}

	def draw(x : float, y : float) {
	    fill(255, 255, 0, 10)
	    rect(x, y, 10, 10)
	    fill(0)
	    text(this.owner.ID.toString, x, y)
	}
	
}
```

Maintenant, on peut coder l'agent Ball:
```
agent BallAgent {
	
	uses DefaultContextInteractions, Drawer
	
	var x : float
  	var y : float
  	var dx : int
  	var dy : int
  
	def randomTo(max : float) : float {
  		return (Math.random * max) as float
	}
	
	on Initialize {
		setSkill(Drawer, new ProcessingDrawer)
		//
		x = width.randomTo + 100.randomTo
		y = height.randomTo
		//
		dx = 1
		dy = 1
	}
	
	on Update {
	    if ((x<=0)||(x> width)) {    
	      dx=dx*(-1)
	    }
	    if ((y<= 0) ||(y> height) ) {    
	      dy=dy*(-1)
	    }
	    x=x+dx
	    y=y+dy
	    emit(new Updated(x, y))
	}

}
```

Maintenant, on peut s'intéresser à l'agent Application qui contrôlera le cycle d'exécution. Ici, on ne peut plus utiliser le mécanisme d'exécution de Janus 1 car la version 2 de Janus exécute tout en parallèle. De plus, il n'est pas possible de créer des instances d'agent et d'accéder aux éléments de cette instance.

Je défini une capacity (et son skill) qui permettra à l'agent application de gérer l'interface graphique:
```
capacity UserInterface {
	def initializeUserInterface(width : float, height : float)
	def drawBackground
	def drawText(message : String)
	def distance(x1 : float, y1 : float, x2 : float, y2 : float) : float
}

skill ProcessingUserInterface implements UserInterface {
	def initializeUserInterface(width : float, height : float) {
		size(width, height)
	}

	def drawBackground {
		background(205)
	}
	
	def drawText(message : String) {
		text(message, 100, 110)
	}

	def distance(x1 : float, y1 : float, x2 : float, y2 : float) : float {
		Math::sqrt((x2-x1)**2 + (y2-y2)**2) as float
	}
}
```

Ensuite, je défini l'agent Application:
```
agent ApplicationAgent {
	
	uses DefaultContextInteractions, UserInterface
	
	var nbAgent : int
	var dernierX : float
	var dernierY : float
	
	on Initialize {
		setSkill(UserInterface, new ProcessingUserInterface)
		// L'agent application est lancé en lui fournissant
		// la taille de la zone graphique en paramètre
		initializeUserInterface(
			Float.valueOf(occurrence.parameters.get(0).toString),
			Float.valueOf(occurrence.parameters.get(1).toString)
		)
		//
		spawn(BallAgent)
		spawn(BallAgent)
		//
		emit(new ApplicationLoopStart)
	}
	
	on ApplicationLoopStart {
		this.nbAgent = 0
		drawBackground()
		emit(new Update)
	}
	
	on Updated {
		synchronized(this) {
			this.nbAgent = this.nbAgent+1
			if (this.nbAgent < (defaultSpace.participants.size - 1)) {
				// Tous les AgentBall ont envoyé Updated
				var distance = distance(
					this.dernierX, this.dernierY,
					occurrence.x, occurrence.y)
				drawText(Float.toString(distance))
				// Démarrage une autre boucle
				emit(new ApplicationLoopStart)
			} else {
				this.dernierX = occurrence.x
				this.dernierY = occurrence.y
			}
		}
	}
	
}
```

Pour lancer l'application, il faut lancer l'application, la méthode la plus simple est de lancer le Jar de Janus depuis la ligne de commande en lui donnant la taille de la fenetre graphique en paramètres.
Il est également possible de lancer Janus depuis un code Java (cf la documentation sur http://www.sarl.io).

**Comment by gallandarakhneorg** [comment]
La solution proposée est une traduction en SARL du code initialement fourni.
Toutefois, il serait peut être préférable que les agents Ball ne puissent pas mettre à jour l'affichage (pas de capacité Drawer), mais que ce soit l'agent Application qui stocke les positions des agents (grâce aux informations x et y dans l'évenement Updated) et réaliser l'affichage des agents.
