### ISSUE TITLE
Open tasks for being included in the release planning

### ISSUE THREAD

**Issue by gallandarakhneorg** [sarl/sarl#332]
Below, I summarize tasks related to improvements or new features that could be interesting in SARL from my point of view. We must discuss them, and put them in a clear release planning (with milestones) as we informally discussed during your previous meetings.

* SARL Core Metamodel:
  * Operational semantic of the event handling (#197, #239, #288, janus-project/janusproject#90).
  * Refactoring of the basic capacities (#72, #76, #78, #106, #224, #291).
  * Space specification, and space implementation in SARL (#105).
  * Implicit synchronization of attributes (#208, #316, #322).
  * Filtering mechanism for behavior registration (#252).
  * Semantic of the `requires` keyword.
  * Holon architecture (#73).
  * Pre- and post-conditions (#9).
* Extension of Xtext tools:
  * Add `assert` keyword, see the [Xtext issue 442320](https://bugs.eclipse.org/bugs/show_bug.cgi?id=442320).
* Environment:
  * Graphical User interface (janus-project/janusproject#110).
  * Physical dimension of the environment.
* Introspection and exploration features:
  * Probing of agent attributes (janus-project/janusproject#110).
* Abstract platform services:
  * Easy deployment of agents via dedicated specifications.
  * Migration of agents.
  * Creation of distributed data structure (useful for creating spaces).
* Extensions:
  * Specification of agents with semi-formal language (see Jnario for an example).
  * Organizational metamodel: CRIO (#225), MOISE.
  * Simulation environment (as user-friendly as NetLogo or Gama), possible base: [jaak](https://github.com/gallandarakhneorg/jaak)
  * Visual programming language that generates SARL.
* Platform-specific tasks:
  * In agents, use constructor-injection in place of method-injection for setting up the builtin capacities (janus-project/janusproject#109)
  * Refactoring of Janus for replacing `new` operators by injected objects when it is useful.
  * Refactoring of the service architecture for avoiding issues (janus-project/janusproject#106, janus-project/janusproject#105, janus-project/janusproject#98, janus-project/janusproject#91, janus-project/janusproject#89, janus-project/janusproject#85, janus-project/janusproject#59, janus-project/janusproject#39).
  * Provide a lightweight platform for embedded systems.

**Comment by srodriguez** [comment]
All issues have been assigned.
