### ISSUE TITLE
SARL features not available in Eclipse Product

### ISSUE THREAD

**Issue by ngaud** [sarl/sarl#399]
When you download the eclipse cocoa product from SARL website, the SARL features are not installed.

**Comment by gallandarakhneorg** [comment]
Which version? stable or unstable?

**Comment by ngaud** [comment]
Finally this is not a real issue, it only happens when the used JDK version is lower than 1.8. The SARL plugins cannot be loaded.

**Comment by gallandarakhneorg** [comment]
I propose to put this issue in the FAQ.
