### ISSUE TITLE
How to be sure that no behavior is running?

### ISSUE THREAD

**Issue by GlennCich** [sarl/sarl#408]
My agent must send an event to another agent when its behaviors have finished their event triggers. 

Currently, I have the following code:

```
agent A {
   var nbRunningBeh = 0
   def inc {
     synchronized(this) { nbRunningBeh ++ }
  }
   def dec {
     synchronized(this) { nbRunningBeh --; if (nbRunningBeh ==0) emit(new IAmFinished) }
  }
  on Initialize {
    registerBehavior(new MyBeh)
  }
}
behavior MyBeh {
   on Event1 {
     (owner as A).inc
     doSomethingLong
     (owner as A).dec
   }
   on Event1 {
     (owner as A).inc
     doSomethingLong
     (owner as A).dec
   }
   on Event2 {
     (owner as A).inc
     doSomethingLong
     (owner as A).dec
   }
   on Event3 {
     (owner as A).inc
     doSomethingLong
     (owner as A).dec
   }
}
```

It would be nice to hide the synchronization between an agent and its behaviors.

**Comment by gallandarakhneorg** [comment]
This issue is close to #288, but extended to all the agent's behaviors.

**Comment by gallandarakhneorg** [comment]
This issue should be fixed with the background changes that will be applied by #459.

**Comment by gallandarakhneorg** [comment]
I propose to extend the `Behaviors` capacity with:
```
def hasRegisteredBehavior : boolean
def getRegisteredBehaviors : Collection<Behavior>
def hasActiveBehavior : boolean
def getActiveBehaviors : Collection<Behavior>
```

Active behaviors are registered behaviors which are running. 
At least, the functions related to registered behaviors must be provided. The functions related to the active behaviors need a discussion.
