### ISSUE TITLE
Guards introduce "double event handling"

### ISSUE THREAD

**Issue by GlennCich** [sarl/sarl#416]
I have the following code:

```
On e [getA() == 1]
{
    setA(-1)
}

On e [getA() != 1]
{
    setA(1)
}

synchronized private def setA(a : int)
{
    this.a = a
}

synchronized private def getA()
{
    return this.a
}
```

When a == 1 and an event e is sent, there is a possibility that first the code of "On e [a == 1]" is executed and a bit later the code of "On e [a != 1]". Hence for the simulation it seems that event e is sent twice, while it is actually sent only once.

When I adjust the code in the following way:

```
On e 
{
    if (getA() == 1)
    {
        setA(-1)
    }
    else if (getA() != 1)
    {
        setA(1)
    }
}
```

The problem seems to be solved.

**Comment by ngaud** [comment]
This is a major issue that will impact the Janus implementation of event dispatching and guard evaluation. That requires to change the whole process for guard evaluation for a given event type where you have various _on_ clause with different guard for the same event type.

The solution is to introduce a additional intermediary function for each event type that will be called before the behaviour to evaluate the various guards before launching the parallel behaviours execution.

In other terms, if you consider an agent A like this:

A {

on E [C1] : H1

on E [C2] : H2

}

You must generate a new method that will sequentially evaluate guards for the event type E and launch when necessary threads for behaviours execution.

E_guardEvaluation {
if (C1) then new thread executing H1
if (C2) then new thread executing H2
}
So it directly impact the considered implementation of the EventBus, currently implemented as a fork of Guava. Basically we need to provide our own EventBus implementation to manage this case.

**Comment by gallandarakhneorg** [comment]
This issue was moved to janus-project/janusproject#116

**Comment by ngaud** [comment]
That will impact the SARL generation for _on_ clauses.

**Comment by gallandarakhneorg** [comment]
The algorithm may be better if:
```
E_guardEvaluation {
l = new List
if (C1) then l.add(H1)
if (C2) then l.add(H2)
for ( a : l) {
   new thread executing a
}
}
```

**Comment by gallandarakhneorg** [comment]
The SARL compiler is fixed for solving the guard evaluation issue.
