### ISSUE TITLE
Add SARL Forum

### ISSUE THREAD

**Issue by gallandarakhneorg** [sarl/sarl#420]
I think GitHub issues is not the best tool for the community for asking questions and having discussions. Github issues are good for SARL implementation discussions, not for SARL usage discussions.

As the Xtext project do, I propose to set a forum platform for SARL users.

**Comment by ngaud** [comment]
OK, vamos.

**Comment by gallandarakhneorg** [comment]
I will try to find a free service that will enable us to us the Github accounts.

**Comment by gallandarakhneorg** [comment]
Perhaps, the best solution is to set up a Google group for SARL.

**Comment by gallandarakhneorg** [comment]
Another solution may be https://gitter.im/

**Comment by gallandarakhneorg** [comment]
https://github.com/integrations/gitter

**Comment by gallandarakhneorg** [comment]
Forums are supported by the SARL google group.
