### ISSUE TITLE
Create SARL Debug perspective and associated debug views

### ISSUE THREAD

**Issue by ngaud** [sarl/sarl#430]
Add specific views for the SARL debugging such as:
* Hierarchy of agents/holons
* Sending event to running agents

**Comment by gallandarakhneorg** [comment]
:+1:

**Comment by gallandarakhneorg** [comment]
This is not a duplicate of #142. Indeed this issue is for a "debugging/run-time" perspective; and Issue #146 is for a "developer" perspective.
