### ISSUE TITLE
Event handler are still executed in parallel to Initialize handler

### ISSUE THREAD

**Issue by gallandarakhneorg** [sarl/sarl#457]
_From @gallandarakhneorg on November 17, 2014 13:57_

Consider the following code:
```
agent Boot {
    uses DefaultContextInteractions
    on Initialize {
        var id1 = spawn(MyAgent)
        emit(new MyEvent, Scopes::addresses(defaultSpace.getAddress(id2)))
    }
}
agent MyAgent {
    on Initialize {
        println("Break point 1")
    }
    on MyEvent {
        println("Break point 2")
    }
}
```

When I put a debugging break point on each `println` and run, the two break points are activated in parallel. It means that the handler for `Initialize` is still no blocking. This is a surprizing behavior for students, and for me since the initialization should be done before every event handler in the agent's lifecycle.  

_Copied from original issue: janus-project/janusproject#90_

**Comment by gallandarakhneorg** [comment]
This issue should be fiexed after the issue #98.

**Comment by gallandarakhneorg** [comment]
This issue will be moved into the SARL project according to sarl/sarl#447.

**Comment by ngaud** [comment]
It was solved during the complete refactor of the agent internal bus, and the additition of a synchronisation to wait until all Initialize behaviors have been processed before continuing.

See io.janusproject.kernel.bic.internaleventdispatching.AgentInternalEventsDispatcher#executeBehaviorMethodsInParalellWithSynchroAtTheEnd
for more details.

It was integrated in SARL with the commit d08b1cd1ab5de0f85e848e43b043e39f1241dc4b
