### ISSUE TITLE
Force update the behavior RUN/DEBUG button in preferences

### ISSUE THREAD

**Issue by ngaud** [sarl/sarl#485]
If you keep the default behaviour of RUN or DEBUG button (launch config) it is a run as, it thus creates automatically a new launch configuration for the agent where your cursor is located inside the code.

That leads to surprising behaviour, because the launched agent is usually the right one.
We need to update the default behaviour in the preferences Preferences/"Run/Debug"/Launching from "Launch the selected resource" to "Always launch the previously launched application"

**Comment by gallandarakhneorg** [comment]
We may also keep the configuration unchanged, but disable by default the "Run As" on the SARL code editor. This "Run As" may be enabled back by using a checkbox in the SARL preferences.

What is the most user friend approach?
