### ISSUE TITLE
Sarl in Android

### ISSUE THREAD

**Issue by haidarknightfury** [sarl/sarl#500]
can sarl be used on android?

**Comment by gallandarakhneorg** [comment]
Running SARL agents on Android is possible under a set of constraints. We have successfully run the Janus platform (the default execution frameork for SARL) on Android after turning off the networking features. The Janus platform uses Zero and Hazelcast libraries for supporting the network. These libraries are not fully functional on Android when we test them last time (1 year ago).

**Comment by gallandarakhneorg** [comment]
Alternatively to the Janus platform,  you could code a new "SARL runtime environment" that is dedicated to Android. This shul not he a hard task but time consuming. Indeed you must provide an implementation of the builtin capacities and anot agent launching class.

**Comment by haidarknightfury** [comment]
what if i use jaCa-android instead?

**Comment by gallandarakhneorg** [comment]
JaCa-android could be used as a SARL runtime environment after you have developed the Java library that is linking the generated SARL classes to the Jason/Jacamo library.
@srodriguez has already developed a library for using Jason in SARL. It will be published soon.

**Comment by gallandarakhneorg** [comment]
Link to the Git repository is: https://github.com/srodriguez/sarl-demos-jason

**Comment by gallandarakhneorg** [comment]
Support of Android studio is discussed in #514 (according to the duplicate and closed issue #530).

**Comment by gallandarakhneorg** [comment]
Two libraries must be ported on Android for enabling the Janus run-time environment to be usable on Android OS:
* ZeroMQ: http://zeromq.org/build:android
* Hazelcast: https://github.com/hazelcast/hazelcast/issues/6102

**Comment by gallandarakhneorg** [comment]
New implementation of Janus, see Issue #751, will provide the necessary API for replacing the networking libraries over Android.
