### ISSUE TITLE
Janus Kernel 2.0.4.1 and SARL 0.4.1 Maven Issues

### ISSUE THREAD

**Issue by Kleptomaniac** [sarl/sarl#503]
Hi,

I am getting issues when trying to install dependencies for both [Janus Kernel 2.0.4.1](https://mvnrepository.com/artifact/io.janusproject/io.janusproject.kernel/2.0.4.1) and [SARL Maven Plugin 0.4.1](https://mvnrepository.com/artifact/io.sarl.maven/sarl-maven-plugin/0.4.1). 

Here is an example error:

~~~~
[ERROR]     Unresolveable build extension: Plugin io.sarl.maven:sarl-maven-plugin:0.4.1 or one of its dependencies could not be resolved: Could not find artifact io.sarl.lang:io.sarl.lang.core:jar:0.4.1 in central (https://repo.maven.apache.org/maven2) -> [Help 2]
~~~~

I believe this relates to the fact that both of those artifacts have dependencies upon [https://mvnrepository.com/artifact/io.sarl.lang/io.sarl.lang.core/0.4.1](https://mvnrepository.com/artifact/io.sarl.lang/io.sarl.lang.core/0.4.1) which appears to not exist?

Cheers,

Matt

**Comment by gallandarakhneorg** [comment]
The `io.sarl.lang.core` Maven module was not accepted on Maven Central. I will fix this issue soon.

**Comment by Kleptomaniac** [comment]
Thanks very much!

**Comment by gallandarakhneorg** [comment]
The module is now available on maven central.
