### ISSUE TITLE
Errors in Maven compiler, not in Eclipse compiler

### ISSUE THREAD

**Issue by Kleptomaniac** [sarl/sarl#504]
Hi,

When building our SARL project via Eclipse, it builds fine with no errors. When building with Maven however, this is the result:

~~~~
[INFO] Validate and generate.
[INFO] Starting validation for input: 'ElevatorSimActions.sarl'
[INFO] Starting validation for input: 'ElevatorSimPercepts.sarl'
[INFO] Starting validation for input: 'ChangeEnvironment.sarl'
[ERROR] ERROR:Invalid implemented type: 'io.sarl.elevatorsim.multiagent.Environment'. Only subtypes of 'io.sarl.lang.core.Capacity' are allowed for 'ChangeEnvironment'. (file:/C:/Users/klep/Documents/SARL%20Elevator%20Project/workspace/sarl-controller/SARLbasicController/src/main/sarl/io/sarl/elevatorsim/multiagent/ChangeEnvironment.sarl line : 13 column : 36)
[ERROR] ERROR:Missing implemented type 'io.sarl.lang.core.Capacity' for 'ChangeEnvironment'. (file:/C:/Users/klep/Documents/SARL%20Elevator%20Project/workspace/sarl-controller/SARLbasicController/src/main/sarl/io/sarl/elevatorsim/multiagent/ChangeEnvironment.sarl line : 13 column : 36)
[ERROR] ERROR:The method enact(ElevatorSimAction) of type ChangeEnvironment must override a superclass method. (file:/C:/Users/klep/Documents/SARL%20Elevator%20Project/workspace/sarl-controller/SARLbasicController/src/main/sarl/io/sarl/elevatorsim/multiagent/ChangeEnvironment.sarl line : 17 column : 2)
[INFO] Starting validation for input: 'ElevatorAgent.sarl'
[INFO] Starting validation for input: 'Environment.sarl'
[INFO] Starting validation for input: 'SimulatorInteraction.sarl'
[ERROR] ERROR:Invalid implemented type: 'io.sarl.elevatorsim.SimulatorPush'. Only subtypes of 'io.sarl.lang.core.Capacity' are allowed for 'SimulatorInteraction'. (file:/C:/Users/klep/Documents/SARL%20Elevator%20Project/workspace/sarl-controller/SARLbasicController/src/main/sarl/io/sarl/elevatorsim/SimulatorInteraction.sarl line : 24 column : 16)
[ERROR] ERROR:The method pushSendCarAction(SendCarAction) of type SimulatorInteraction must override a superclass method. (file:/C:/Users/klep/Documents/SARL%20Elevator%20Project/workspace/sarl-controller/SARLbasicController/src/main/sarl/io/sarl/elevatorsim/SimulatorInteraction.sarl line : 84 column : 5)
[INFO] Starting validation for input: 'SimulatorProxyAgent.sarl'
[INFO] Starting validation for input: 'SimulatorPush.sarl'
[ERROR] Execution failed due to a severe validation error.
~~~~

This appears as if it is similar to #380. For reference, we are currently building with SARL Maven Plugin 0.4.0 due to #503.

If it helps, I can provide some of the problem files or our pom.xml.

Cheers,

Matt

**Comment by Kleptomaniac** [comment]
For reference also, I am using SARL Eclipse version 0.4.1, as this was the only available stable download at http://www.sarl.io//download/index.html. Could this be the cause of the issue?

**Comment by gallandarakhneorg** [comment]
Could you give me the content of the file `SimulatorInteraction.sarl`. I think it will be enough for reproducing the issue.

**Comment by Kleptomaniac** [comment]
Sure. Here is SimulatorInteraction.sarl:

~~~~
/**
 * 
 */
package io.sarl.elevatorsim

import io.sarl.elevatorsim.events.CarRequestPercept
import io.sarl.elevatorsim.events.DoorClosedPercept
import io.sarl.elevatorsim.events.DoorOpenedPercept
import io.sarl.elevatorsim.events.DoorSensorClearedPercept
import io.sarl.elevatorsim.events.FloorRequestPercept
import io.sarl.elevatorsim.events.PersonEnteredPercept
import io.sarl.elevatorsim.events.PersonExitedPercept
import io.sarl.elevatorsim.events.SendCarAction
import io.sarl.lang.core.EventSpace
import io.sarl.wrapper.ClientController
import java.io.IOException
import io.sarl.elevatorsim.events.ModelChangePercept

/**
 * @author klep
 *
 */
skill SimulatorInteraction extends ClientController 
    implements SimulatorPush
{
    private var userAgentSpace : EventSpace

    new(host : String, port : int, userAgentSpace : EventSpace) 
        throws IOException
    {
        super(host, port)
        this.userAgentSpace = userAgentSpace
    }

    override onModelChanged(id : int, time : long, newModel : ModelHolder)
        throws IOException
    {
        userAgentSpace.emit(new ModelChangePercept(time, id, newModel))
    }

    override onCarRequested(id : int, time : long, floor : int, 
        direction : String) throws IOException 
    {
        val up = direction.equals("up");
        userAgentSpace.emit(new CarRequestPercept(time, id, floor, up))
    }

    override onDoorOpened(id : int, time : long, floor : int,
        car : int) throws IOException 
    {
        userAgentSpace.emit(new DoorOpenedPercept(time, id, car, floor))
    }

    override onDoorClosed(id : int, time : long, floor : int,
        car : int) throws IOException 
    {
        userAgentSpace.emit(new DoorClosedPercept(time, id, car, floor))
    }

    override onDoorSensorClear(id : int, time : long, floor : int,
        car : int) throws IOException 
    {
        userAgentSpace.emit(new DoorSensorClearedPercept(time, id, car, floor))
    }

    override onPersonEnteredCar(id : int, time : long, car : int) 
        throws IOException 
    {
        userAgentSpace.emit(new PersonEnteredPercept(time, id, car))
    }

    override onPersonLeftCar(id : int, time : long, car : int) 
        throws IOException 
    {
        userAgentSpace.emit(new PersonExitedPercept(time, id, car))
    }

    override onFloorRequested(id : int, time : long, floor : int,
        car : int) throws IOException 
    {
        userAgentSpace.emit(new FloorRequestPercept(time, id, car, floor))
    }

    override pushSendCarAction(action : SendCarAction)
    {
        try 
        {
            sendCar(action.car, action.floor, action.nextDirection,
                null, null);
        } 
        catch (e : IOException) 
        {
            e.printStackTrace();
        }
    }
}
~~~~

Just in case, here is SimulatorPush.sarl (capacity SimulatorInteraction implements) also:

~~~~
/**
 * 
 */
package io.sarl.elevatorsim

import io.sarl.elevatorsim.events.SendCarAction

/**
 * @author klep
 *
 */
capacity SimulatorPush {
    def pushSendCarAction(action : SendCarAction)
}
~~~~

If you need anything else, let me know!

Cheers,

Matt

**Comment by gallandarakhneorg** [comment]
Could you provide me the list of your Maven dependencies to SARL/Janus with the versions?

**Comment by Kleptomaniac** [comment]
Currently we depend on io.janusproject.kernel 2.0.4.0 and io.sarl.maven.sarl-maven-plugin 0.4.0 (have not had a chance yet to update to 2.0.4.1 and 0.4.1 respectively as of yet). Here is our pom.xml for reference:

~~~~
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>sarl-controller</groupId>
	<artifactId>sarl-controller</artifactId>
	<version>0.3.2</version>
    <properties>
        <janus.version>2.0.4.0</janus.version>
        <sarl.version>0.4.0</sarl.version>
        <json.version>20160810</json.version>
        <compiler.level>1.8</compiler.level>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
	</properties>
	
    <build>
        <plugins>
            <plugin>
                <groupId>io.sarl.maven</groupId>
                <artifactId>sarl-maven-plugin</artifactId>
                <version>${sarl.version}</version>
                <extensions>true</extensions>
                <configuration>
                    <source>${compiler.level}</source>
                    <target>${compiler.level}</target>
                    <encoding>${project.build.sourceEncoding}</encoding>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <dependencies>
        <dependency>
            <groupId>io.janusproject</groupId>
            <artifactId>io.janusproject.kernel</artifactId>
            <version>${janus.version}</version>
        </dependency>
        <dependency>
            <groupId>org.json</groupId>
            <artifactId>json</artifactId>
            <version>${json.version}</version>
        </dependency>
    </dependencies>
</project>
~~~~

**Comment by Kleptomaniac** [comment]
I have now updated io.janusproject.kernel to 2.0.4.1 and io.sarl.maven.sarl-maven-plugin to 0.4.1, however the same issue persists (compiles fine in Eclipse, not on CLI).

**Comment by gallandarakhneorg** [comment]
Not surprising, the issue is due to the injection of the software modules that seems to be different in the Eclipse and Maven versions of the compiler.

**Comment by gallandarakhneorg** [comment]
I have difficulties to reproduce the issue. Could you send to me by email (stephane.galland@utbm.fr) a zip file of your source code (including the maven pom) in which the not relevant files are removed.

Could you also given the output of: `mvn --version`.

**Comment by Kleptomaniac** [comment]
Thanks for help. I have sent you a private email including our project source code, including our pom.xml. Furthermore, my Maven version is Maven 3.3.9.

**Comment by gallandarakhneorg** [comment]
For keeping track of the error cause, the problem is due to the invalid generation of the Java files.

For example, from the following SARL code:
```
capacity Environment
{
	def enact(action : ElevatorSimAction)
}
```

The generated Java code is:
```java
public class Environment{
}
```

But it should be:
```java
public interface Environment extends Capacity{
    void enact(ElevatorSimAction action);
}
```

**Comment by gallandarakhneorg** [comment]
The plugin works on Linux; but not on Windows.

**Comment by gallandarakhneorg** [comment]
| Operating System | Compilation status |
|--------------------------|----------|
| Linux Ubuntu 16.04 | ok |
| Windows XP | ok |

**Comment by ssardina** [comment]
@gallandarakhneorg : I want to report against this issue my experience. As a background I am running Linux (Mint), Maven 3.3.9, JDK 1.8.0_101.

1) I can compile and run our system all from CLI with SARL 0.4.1 and Janus 2.0.4.1. This is our version 0.3.3

I do `mvn install` and then this to run the system as follows using the ECLIPSE version of Janus:

`java -cp ~/.m2/repository/sarl-controller/sarl-controller/0.3.3/sarl-controller-0.3.3.jar:/home/ssardina/opt/sarl-0.4.1/plugins/io.janusproject.plugin_0.4.1.jar io.janusproject.Boot io.sarl.elevatorsim.SimulatorProxyAgent`

So all good there. I think @Kleptomaniac  cannot do this in his Windows install.

2) For some reason I do not understand, it does NOT run if instead I use the janus jar file in ~/.m2:

```
$ java -cp ~/.m2/repository/sarl-controller/sarl-controller/0.3.3/sarl-controller-0.3.3.jar:/home/ssardina/.m2/repository/io/janusproject/io.janusproject.plugin/0.4.1/io.janusproject.plugin-0.4.1.jar io.janusproject.Boot io.sarl.elevatorsim.SimulatorProxyAgent
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/cli/ParseException
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.cli.ParseException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more

```

The only difference is that the JAR file for Janus is the one obtained via Maven in ~/.m2, I would have imagine they are the same as the one shipped with ECLIPSE. But maybe I am missing somthing here due to lack of experience :-)


2) I can compile but CANNOT run our system from CLI with SARL 0.5.0-SNAPSHOT and Janus 2.0.5.0-SNAPSHOT. This is our version 0.3.4

For this version, I have this in pom.xml:

```
        <janus.version>2.0.5.0-SNAPSHOT</janus.version>
        <sarl.version>0.5.0-SNAPSHOT</sarl.version>

```

Then `mvn install` correctly generates file:

`/home/ssardina/.m2/repository/sarl-controller/sarl-controller/0.3.4/sarl-controller-0.3.4.jar`

But then the system does not work with neither the Janus in the ECLIPSE package or the one downloaded automatically by Maven:

```
[ssardina@ssardina-Latitude-E7440 sarl-controller]$ java -cp ~/.m2/repository/sarl-controller/sarl-controller/0.3.4/sarl-controller-0.3.4.jar:/home/ssardina/.m2/repository/io/janusproject/io.janusproject.plugin/0.5.0-SNAPSHOT/io.janusproject.plugin-0.5.0-SNAPSHOT.jar io.janusproject.Boot io.sarl.elevatorsim.SimulatorProxyAgent
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/cli/ParseException
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.cli.ParseException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more

```

Same result if I use the JAR for Janus that comes with ECLIPSE distro 0.5.0.


OK that's all I can report. Again, I may be missing something myself in my install. In my understanding I should be able to run everything using the JAR files from the Maven storage in ~/.m2.

Happy to provide more details, I tried to be as clear and complete as possible.

Cheers

Sebastian

**Comment by Kleptomaniac** [comment]
Hi @gallandarakhneorg,

So just for reference in the issue, this is the specs of my machine:

**OS:** Windows 10
**JRE:** 1.8.0_66

I have tried both the combination of **SARL 0.4.1 and Janus 2.0.4.1** and **SARL 0.5.0-SNAPSHOT and Janus 2.0.5.0-SNAPSHOT** and the results appear to be the same as before the issue was closed, i.e. Java code generation is incorrect. So for example, in my class stubs, this SARL code:

~~~~
capacity Environment
{
	def enact(action : ElevatorSimAction)
}
~~~~

results in this generated Java code:

~~~~
public class Environment{
}
~~~~

which is the same as before.

Hope this helps to resolve the issue,

Matt

**Comment by gallandarakhneorg** [comment]
Dear @ssardina.

In the following command line is not the good one:
```
java -cp ~/.m2/repository/sarl-controller/sarl-controller/0.3.3/sarl-controller-0.3.3.jar:/home/ssardina/.m2/repository/io/janusproject/io.janusproject.plugin/0.4.1/io.janusproject.plugin-0.4.1.jar io.janusproject.Boot io.sarl.elevatorsim.SimulatorProxyAgent
```

Why is it not the good one?

The `io.janusproject.plugin` module contains the compiled of the Janus platform, but not the classes of the other libraries that are needed running Janus. Consequently, when you launch the application with a standard Java approach, class files are missed from the classpath.

For solving this issue, you could use two approaches:
* Use maven for running the application. Maven has all the dependencies in its configuration, and is able to build the correct classpath: update the pom.xml file for specifying the main class to be run, and launch `mvn exec:java`
* Use the standard Java launching approach (as you tried) with the correct Jar file for Janus. You need to download the jar file that contains all the needed class for running Janus: http://maven.sarl.io/io/janusproject/io.janusproject.kernel/2.0.5.0-SNAPSHOT/io.janusproject.kernel-2.0.5.0-20161004.030955-7-with-dependencies.jar ; then you could use the following command line:
```
java -cp ~/.m2/repository/sarl-controller/sarl-controller/0.3.3/sarl-controller-0.3.3.jar:/path/to/io.janusproject.kernel-2.0.5.0-with-dependencies.jar io.janusproject.Boot io.sarl.elevatorsim.SimulatorProxyAgent
```

We have planed to make the things easier from the CLI, see #149.

Stéphane.

**Comment by gallandarakhneorg** [comment]
The POM that I'm using for compiling your code template is:
```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>sarl-controller</groupId>
	<artifactId>sarl-controller</artifactId>
	<version>0.3.2</version>
    <properties>
        <janus.version>2.0.5.0-SNAPSHOT</janus.version>
        <sarl.version>0.5.0-SNAPSHOT</sarl.version>
        <json.version>20160810</json.version>
	</properties>

	<build>
        <plugins>
            <plugin>
                <groupId>io.sarl.maven</groupId>
                <artifactId>sarl-maven-plugin</artifactId>
                <version>${sarl.version}</version>
                <extensions>true</extensions>
                <configuration>
                    <source>${compiler.level}</source>
                    <target>${compiler.level}</target>
                    <encoding>${project.build.sourceEncoding}</encoding>
                </configuration>
            </plugin>
        </plugins>
	</build>

    <dependencies>
        <dependency>
            <groupId>io.sarl.maven</groupId>
            <artifactId>io.sarl.maven.sdk</artifactId>
            <version>${sarl.version}</version>
        </dependency>
<!--        <dependency>-->
<!--            <groupId>io.janusproject</groupId>-->
<!--            <artifactId>io.janusproject.kernel</artifactId>-->
<!--            <version>${janus.version}</version>-->
<!--        </dependency>
-->
        <dependency>
            <groupId>org.json</groupId>
            <artifactId>json</artifactId>
            <version>${json.version}</version>
        </dependency>
    </dependencies>

<repositories>
	  <repository>
	    <id>io.sarl-maven</id>
	    <name>SARL Snapshots</name>
	    <url>http://maven.sarl.io/</url>
	  </repository>
	</repositories>
	<pluginRepositories>
    	  <pluginRepository>
	    <id>io.sarl-maven</id>
	    <name>SARL Snapshots</name>
	    <url>http://maven.sarl.io/</url>
	    <snapshots>
	      <enabled>true</enabled>
	    </snapshots>
	  </pluginRepository>
	</pluginRepositories>

</project>
```

**Comment by gallandarakhneorg** [comment]
Dear @Kleptomaniac.
could you give me the path to file Java source file that you have shown to me above?
Is this file in the `target` folder or the `src/main/generated-sources/sarl` folder?

**Comment by Kleptomaniac** [comment]
This Java source file is in the
```target/xtext-temp/stubs/io/sarl/elevatorsim/multiagent``` directory of
our SARL project.

**Comment by Kleptomaniac** [comment]
This Java source file is in the ```target/xtext-temp/stubs/io/sarl/elevatorsim/multiagent``` directory of our SARL project.

**Comment by Kleptomaniac** [comment]
Ah, my apologies, I see. The ```generated-sources/sarl``` folder correctly compiles the Java source files.

**Comment by Kleptomaniac** [comment]
As for differences in pom.xml, the only major differences I see are the commenting out of the ```io.janusproject.kernel``` dependency and the addition of the ```io.sarl.maven.sdk``` dependency.

Thanks very much for your help so far, sorry to be such a bother!

**Comment by gallandarakhneorg** [comment]
Dear @Kleptomaniac.

Regarding the maven dependencies, using `io.sarl.maven.sdk` is the preconized approach. This module gives you all the libraries from the public API of SARL. Usually, I use `io.janusproject.kernel` in two specific cases: when I'm using a function that is in the Janus platform and not in the SARL API library, or when I want to run my SARL application when `mvn exec:java`. In the other cases, I'm using the `io.sarl.maven.sdk`.

Now, if the Java file is correctly generated, you could check if the class file is the good one. For checking that point, you could use the `javap` disassembler on one of the class files (in the folder `target/classes`). If the `javap` tool shows you a content that is similar to the original SARL code; every thing is going in the right direction. Please let me know.

**Comment by ssardina** [comment]
Dear @gallandarakhneorg ,

Thanks a lot for following up so quickly.  Seems we are discussing now two related but different issues: running on CLI and compiling in Windows. I was going to open a new thread for the CLI but since it may now all be resolved, not sure you want that.

So, regarding running on CLI:

1)  I can compile and run with maven perfectly. But I wanted to understand and be able to run it without Maven, from first-principle so to say :-)

2) Your explanation for CLI makes total sense. I did try indeed the kernel jar as I thought that the plugin was to compile SARL into java, and the kernel to actually run it. But I did not have the kernel -with-dependencies and I was using the kernel that was in ~/.m2, which I check now and has no classes inside! Seems the full jar with dependencies is not downloaded by Maven, but I now got both the 2.0.4 and 2.0.5 and I was able to run on CLI both versions. 

So, all good, I can now run with Maven and CLI. Thanks!

Now, given my experience, I think it would be good to have this a bit more clear on the documentation. All the doc pages I could find assume that Janus has been packed with the application in the same JAR (not sure how that would be done). This is the case for:

1) the demo page ( http://www.sarl.io/docs/suite/io/sarl/docs/tutorials/AgentCommunicationWithThePingPongAgentsSpec.html) 
2) how to run SARL from CLI (http://www.sarl.io/docs/suite/io/sarl/docs/gettingstarted/RunSARLAgentFromTheCommandLineSpec.html)

Would be good in 2 at least to explain what happens when app.jar does not contain the JANUS/SARL and that one needs to use the kernel-with-dependencies. Something like this:

> If app.jar does not include the JANUS/SARL runtime execution engine, we also need to include the Janus Kernel with all the dependencies into the class file:
> 
> java -cp app.jar:/path/to/io.janusproject.kernel-<version>-with-dependencies.jar io.janusproject.Boot myapp.MyAgent

Just my 5c, thanks.

Sebastian




Thanks!

**Comment by gallandarakhneorg** [comment]
Dear @ssardina 
Thank you for your fedback.
I fully agree with you on the lake of explanation in the documentation.
I have started to update the documentation. It will be updated on the website as soon as we solve Issue #478, which is related to the tool we have used for generating the documentation and the tutorials and that is no more working unfortunately.

**Comment by gallandarakhneorg** [comment]
See #513 for the issue related to the update of the documentation.

**Comment by gallandarakhneorg** [comment]
I have reproduced the issue on Windows 10 platform. I'm working on the bug detection and fix now.

**Comment by gallandarakhneorg** [comment]
The fixes will need 1 week of work.

**Comment by ssardina** [comment]
That is great Stephane that you can reproduce on your side and you have an
idea of the effort, thanks!

Let us know if you need anything from our side with Matt.

**Comment by gallandarakhneorg** [comment]
I have published a new Maven plugin for the SARL compiler.
Use the following command-line options for ensuring you have the lastest version:
```
mvn -U -up clean install
```


| Operating System | Compilation status | Maven | JDK |
|--------------------------|--------------------------|-----------|-------|
| Linux Ubuntu 16.04 | success | 3.3.9 | 1.8.0_101 |
| Windows 10 | success | 3.3.9 | 1.8.0_91 |
| Windows XP | success | 3.3.9 | 1.8.0_92 |

**Comment by gallandarakhneorg** [comment]
Please reopen if still failing.

**Comment by ssardina** [comment]
Thanks @gallandarakhneorg . I do not have Windows but Matt was going to test it and hopefully it will remain closed!

**Comment by Kleptomaniac** [comment]
Hi @gallandarakhneorg, sorry for the slow response to this thread, its been a busy couple of weeks! It appears as if my issues are gone on Windows 10 as of the moment when using 0.5.0-SNAPSHOT of SARL Maven Plugin and 2.0.5.0-SNAPSHOT of Janus Project Kernel!

Thanks very much! I will let you know if any other significant issues arise!

**Comment by gallandarakhneorg** [comment]
That's a great news. I will start the release plan for the version 0.4.2 in order to provide a stable version with the patches. Thank you for initial issue submission.
