### ISSUE TITLE
Reference instance methods or fields in abstract class

### ISSUE THREAD

**Issue by Kleptomaniac** [sarl/sarl#505]
I am unable to reference instance methods or fields within an abstract class anywhere but the constructor. For example, I am unable to do this:

~~~~
abstract class TestClass {

	private var testString : String;
	
	public new(testString : String)
	{
		this.testString = testString;
	}
	
	public def getTestString() : String
	{
		return this.testString;
	}
}
~~~~

The error I get is ```The method or field this is undefined``` for the ```this``` in ```getTestString```. Is there some other way I should be accessing instance methods and fields? If there is no way is there another method of doing something similar? It seems redundant to allow the private modifier to be used on fields and methods in abstract classes if they cannot then be accessed.

Cheers,

Matt

**Comment by gallandarakhneorg** [comment]
Could you try:
```
abstract class TestClass {

    private var testStringField : String;

    public new(testString : String)
    {
        this.testString = testString;
    }

    public def getTestString() : String
    {
        return this.testStringField;
    }
}
```
Indeed, in SARL, the call to the function "this.getTestString()" may be written "this.testString". I would like to determine if there is a conflict in the compiler between the field and the call to `getTestString`.

Nevertheless, I will add this use case in the unit tests, and solve this issue.

**Comment by Kleptomaniac** [comment]
Hi,

No, that doesn't appear to solve it. It doesn't seem as if it is specific to getters, it seems as if it applies to any instance method or field. As a more general example, this also does not compile:

~~~~
abstract class TestClass {
    public def testMethod1 {
        this.testMethod2()
    }

    public def testMethod2 { }
}
~~~~

**Comment by gallandarakhneorg** [comment]
Ok. I will work on this issue for next week.

**Comment by gallandarakhneorg** [comment]
This issue is due to the invalid generation of the methods when the containing type is abstract. The generated Java methods are marked as abstract even if a block of code is given in SARL.
