### ISSUE TITLE
Explain how to launch Janus in the documentation.

### ISSUE THREAD

**Issue by gallandarakhneorg** [sarl/sarl#513]
Documentation is missing clear explanations on how to launch a Janus application without or without Maven, and without or without the standard Java launching approach.

**Comment by gallandarakhneorg** [comment]
Discussion in Issue #504 gives the base guidelines to be provided by the documentation.

**Comment by ssardina** [comment]
Brilliant. Just to help out this is what I quickly wrote for our application:

To compile: 

1. Make sure `pom.xml` is correctly configured (with correct SARL and JANUS versions) 
2. Run either: 

- `mvn compile` or `mvn clean compile` to generate a final jar file under ~/.m2 
- `mvn compile` and then `mvn packag`e to generate the compile + jar file in current dir under subdir target/

To run using Maven (which will take care of all dependencies needed for the SARL application):

`mvn exec:java -Dexec.mainClass="io.janusproject.Boot" -Dexec.args=io.sarl.elevatorsim.SimulatorProxyAgent
`

To run using plain Java we need to include the Janus Kernel JAR file containing Janus execution engine:

`java -cp /path/to/sarl-controller-<version>.jar:/path/to/io.janusproject.kernel-<version>-with-dependencies.jar io.janusproject.Boot io.sarl.elevatorsim.SimulatorProxyAgent
`
The Janus execution engine can be found at:

http://www.janusproject.io/
http://maven.sarl.io/io/janusproject/io.janusproject.kernel

**Comment by gallandarakhneorg** [comment]
The major Janus command line options should also be explained.
