### ISSUE TITLE
Complete the content of the Initialize event with the ID of its potential super-holon and the ID of its spawner

### ISSUE THREAD

**Issue by ngaud** [sarl/sarl#515]
A nice additional simple feature would be to extend the current definition of the Initialize event to add a two new fields
- parent: the ID of the parent holon if it exists, null otherwise.
- spawner: the ID of the agent that has spawned this agent, JANUS_ID if it is the platform itself

**Comment by gallandarakhneorg** [comment]
Is the `parent` identifier the same identifier of the default context of the spawned agent (assuming the context id is equal to the super-agent id)?
