### ISSUE TITLE
Consider the possibility to integrate a syntax for the try with ressource in on clauses.

### ISSUE THREAD

**Issue by ngaud** [sarl/sarl#517]
Verify if xbase manages [try-with-resource](https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html) syntax and if yes enable it in SARL.

**Comment by gallandarakhneorg** [comment]
See [discussion](https://www.eclipse.org/forums/index.php/t/1081906/) on the Xtext forum.

**Comment by gallandarakhneorg** [comment]
Xtext issue tracker has two issues related to the tr-with-resource syntax:
- https://bugs.eclipse.org/bugs/show_bug.cgi?id=457593
- https://bugs.eclipse.org/bugs/show_bug.cgi?id=366020
