### ISSUE TITLE
Agent not found in launch config

### ISSUE THREAD

**Issue by Lomadriel** [sarl/sarl#527]
io.sarl.demos.gameoflife.environment.agent.Boot is not provided by the launch configuration dialog.
cf: https://github.com/TiWinDeTea/sarl-game-of-life/commit/f948ad4846d06efd6d39a0143b1c7851f42611d6

**Comment by gallandarakhneorg** [comment]
This issue cannot be reproduced, even with a copy of your Eclipse workspace.
Please reopen this issue of the problem is still present, and send a copy of your workspace (with `.metadata`) to me by email.
