### ISSUE TITLE
Cant run agents, java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by vincetrencsenyi** [sarl/sarl#531]
I tried both the preconfigured version of eclipse, and installing from the update site.
I followed the instructions for the Run configurations, and it is the case with the example projects as well.
I always get "Exception in thread "main" java.lang.NoClassDefFoundError: io/janusproject/Messages
	at io.janusproject.Boot.main(Boot.java:375)"
Not sure what I am missing.

**Comment by gallandarakhneorg** [comment]
Are you using using version 0.4.2?

**Comment by gallandarakhneorg** [comment]
In the hierarchical view of your project (package explorer), you could open the dependency that is corresponding to `io.janusproject.plugin` jar file and checks if the file `io/janusproject/Messages.class` is present. If not, please give me back the version number of the jar file.

**Comment by gallandarakhneorg** [comment]
Note that this issue can be reproduced in the standalone product and not as debugged application in the Eclipse-DSL environment.

**Comment by gallandarakhneorg** [comment]
The hidden exception is:
```
org/eclipse/osgi/util/NLS
java.lang.NoClassDefFoundError: org/eclipse/osgi/util/NLS
```
