### ISSUE TITLE
Crash when autoCompletion on package

### ISSUE THREAD

**Issue by galoat** [sarl/sarl#552]
When I try to auto complet after the keyWord  "import" Eclipse Sarl crash.

Version: 0.4.2
Build id: 20161028145141 (2016-10-28)

**Comment by gallandarakhneorg** [comment]
Have you still the Eclipse log file (it should be located in the Eclipse binary folder or the workspace folder).
This file should contains the exception that is the cause of the crash.

Could you also specify your operating system for helping me to reproduce the issue?

**Comment by gallandarakhneorg** [comment]
I cannot reproduce the issue. I need more information on the error and the platform.

**Comment by galoat** [comment]
I'm on a Mac (OS X El capitain)
I can't find the bin  folder inside the Eclipse Sarl application or in my workspace

**Comment by gallandarakhneorg** [comment]
Thank you. The log file should be in the same folder as the one containing the executable file of the SARL product, or in the folder `<workspace directory>/.metadata`.

**Comment by gallandarakhneorg** [comment]
Configuration of the MacOS product has been changed. Reopen this issue if the product still hangs up on autocompletion.
