### ISSUE TITLE
Let's provide the possibility to launch agent with a name

### ISSUE THREAD

**Issue by ngaud** [sarl/sarl#60]
The constraint is that this name must be unique.
But in this case, we need a central name repository to guarantee the unicity of the agent's name.
Using this name we can then generate automatically the ID.

Let's provide the possibility for the user to overload this name.

**Comment by srodriguez** [comment]
@ngaud Could you provide some details on the use case?

**Comment by srodriguez** [comment]
If you intend to show some human-readable name, you can use the Logging capacity that accepts a different name than the Agent ID.
On the other, if you what to share this readable name among agents it should be defined in the address of your space specification.
