### ISSUE TITLE
Stable product download

### ISSUE THREAD

**Issue by romainhry** [sarl/sarl#602]
Download the lastest stable version of SARL on mac OS X is not available.

"Not Found

The requested URL /io/sarl/io.sarl.lang.updatesite/0.4.3/io.sarl.lang.updatesite-0.4.3-macosx.cocoa.x86_64.zip was not found on this server."

**Comment by gallandarakhneorg** [comment]
Thanks. I will fix this issue by today.

**Comment by romainhry** [comment]
It's still not working, isn't it ?

**Comment by gallandarakhneorg** [comment]
It's not working. Please wait for the next stable release that will be published during the week end.
