### ISSUE TITLE
Enable the use of instance-related variables or functions within parameters default value.

### ISSUE THREAD

**Issue by ngaud** [sarl/sarl#612]
Currently, we can only use "static" variable/function within parameters default value. 
The idea is to extend this definition.

A solution could be the use of a provider (in the sense of Injection, IoC) to provide the parameters default value when it is necessary, and this approach could also be used to validate other dynamic instances related pre-conditions.

**Comment by gallandarakhneorg** [comment]
It's fully possible. Currently, the default value expressions are inferred to static hidden fields.
Changing the code generator in order to infer to non static hidden functions is possible. These functions will contains the default value expression.

So that:
```
class Example {
	var myfield : int
	def fct(a : int = myfield + 5) {
		
	}
}
```
should be inferred to:
```
public class Example {
  private int myfield;
  
  @DefaultValueSource
  public void fct(@DefaultValue("Example#FCT_0") final int a) {
  }
  
  /**
   * Default value for the parameter a
   */
  @SyntheticMember
  @SarlSourceCode("43 + 5")
  private final int $DEFAULT_VALUE$FCT_0() {
     return (myfield + 5);
  }
  
  @DefaultValueUse("int")
  @SyntheticMember
  public final void fct() {
    fct($DEFAULT_VALUE$FCT_0());
  }
  
  @Override
  @Pure
  @SyntheticMember
  public boolean equals(final Object obj) {
    if (this == obj)
      return true;
    if (obj == null)
      return false;
    if (getClass() != obj.getClass())
      return false;
    Example other = (Example) obj;
    if (other.myfield != this.myfield)
      return false;
    return super.equals(obj);
  }
  
  @Override
  @Pure
  @SyntheticMember
  public int hashCode() {
    final int prime = 31;
    int result = super.hashCode();
    result = prime * result + this.myfield;
    return result;
  }
  
  @SyntheticMember
  public Example() {
    super();
  }
}
```

**Comment by gallandarakhneorg** [comment]
Additionally, I think we could use the two generation approaches:
* if the expression contains only static elements, the current generation should be used.
* if the expression contains not static elements, the new generation mechanism should be used.

**Comment by gallandarakhneorg** [comment]
One issue is remaining: default values to the constructor's parameters must be defined as static because there is no instance yet.

**Comment by gallandarakhneorg** [comment]
According to comments I have received from the Software Engineering community on one of my paper, we must defined the static and dynamic semantics of that point prior to its implementation.
