### ISSUE TITLE
One of the most embarassing bug come from IDE extension 

### ISSUE THREAD

**Issue by romainhry** [sarl/sarl#687]
Sometimes all my code became red with the explanation as follow : "the return type is incompatible with equals(Object)". To solve it, I delete a space and save my file.
<img width="364" alt="capture d ecran 2017-06-25 a 00 50 42" src="https://user-images.githubusercontent.com/15669668/27512568-250bfaa2-5945-11e7-83f1-4e67d8b85386.png">

**Comment by gallandarakhneorg** [comment]
That's a now issue that is under review.
As indicated in Issue #661, the bug was forwarded to the Xtext library, which provide the editor.
This editor's problem seems generating "strange" errors such as your or the of of Issue #673.

**Comment by romainhry** [comment]
Ok thanks.
It was just to inform you : it's perhaps the last day that I will use SARL even if, I should admit, it's quite comfortable.
Good luck for solving this issue !

**Comment by romainhry** [comment]
***It will probably never be used again because I'm in LEIM.
I wanted to explicate. Sorry

**Comment by gallandarakhneorg** [comment]
No problem.

**Comment by gallandarakhneorg** [comment]
Duplicate of #661.
