### ISSUE TITLE
Incorrect generic method compilation

### ISSUE THREAD

**Issue by hypnobunny** [sarl/sarl#720]
Hi,

In SARL 0.5.7, compiling this capacity:

~~~java
package example

capacity ExampleCapacity 
{    
    def exampleMethod(clazz : Class<T>) with T
}
~~~

results in this generated Java source:

~~~java
package example;

import io.sarl.lang.annotation.SarlElementType;
import io.sarl.lang.annotation.SarlSpecification;
import io.sarl.lang.core.AgentTrait;
import io.sarl.lang.core.Capacity;

@FunctionalInterface
@SarlSpecification("0.5")
@SarlElementType(17)
@SuppressWarnings("all")
public interface ExampleCapacity extends Capacity {
  public abstract <T extends Object> void exampleMethod(final Class<T> clazz);
  
  public static class ContextAwareCapacityWrapper<C extends ExampleCapacity> extends Capacity.ContextAwareCapacityWrapper<C> implements ExampleCapacity {
    public ContextAwareCapacityWrapper(final C capacity, final AgentTrait caller) {
      super(capacity, caller);
    }
    
    public void exampleMethod(final Class<?> clazz) {
      try {
        ensureCallerInLocalThread();
        this.capacity.exampleMethod(clazz);
      } finally {
        resetCallerInLocalThread();
      }
    }
  }
}
~~~

This code results in an error: 
```Java problem: Name clash: The method exampleMethod(Class<?>) of type ExampleCapacity.ContextAwareCapacityWrapper<C> has the same erasure as exampleMethod(Class<T>) of type ExampleCapacity but does not override it```

I believe the issue is that the SARL compilation procedure erases the generic type argument for the capacity wrapper in favour of a wildcard. As such, I believe that this should be the correctly compiled Java source:

~~~java
package example;

import io.sarl.lang.annotation.SarlElementType;
import io.sarl.lang.annotation.SarlSpecification;
import io.sarl.lang.core.AgentTrait;
import io.sarl.lang.core.Capacity;

@FunctionalInterface
@SarlSpecification("0.5")
@SarlElementType(17)
@SuppressWarnings("all")
public interface ExampleCapacity extends Capacity {
  public abstract <T extends Object> void exampleMethod(final Class<T> clazz);
  
  public static class ContextAwareCapacityWrapper<C extends ExampleCapacity> extends Capacity.ContextAwareCapacityWrapper<C> implements ExampleCapacity {
    public ContextAwareCapacityWrapper(final C capacity, final AgentTrait caller) {
      super(capacity, caller);
    }
    
    public <T extends Object> void exampleMethod(final Class<T> clazz) {
      try {
        ensureCallerInLocalThread();
        this.capacity.exampleMethod(clazz);
      } finally {
        resetCallerInLocalThread();
      }
    }
  }
}
~~~

Regards,
Matthew McNally

**Comment by gallandarakhneorg** [comment]
Thank you for detecting this issue.
The Java inferrer's function which copies of the prototypes of the functions does not copy the type parameters (T) and the declared exceptions.
It will be fixed asap.

**Comment by hypnobunny** [comment]
Thanks @gallandarakhneorg. Will this become stable in 0.6 or are there plans for an 0.5.8?

**Comment by gallandarakhneorg** [comment]
Release 0.6 is planned for mid September 2017.
Could you wait until this time?

**Comment by hypnobunny** [comment]
Hi @gallandarakhneorg, I would not like to be a burden on your resources, but unfortunately I am on a very tight deadline at the moment and this feature is rather crucial to my program API. Would you be able to release an intermediary patch including this fix?

Thanks very much,
Matthew McNally

**Comment by hypnobunny** [comment]
As an addendum to this issue, I have also run into this capacity definition not working:

~~~
package example

capacity ExampleCapacity 
{    
    def exampleMethod(plan : (T) => void) with T
}
~~~

This again results in the error ```Java problem: The type ExampleCapacity.ContextAwareCapacityWrapper<C> must implement the inherited abstract method ExampleCapacity.exampleMethod(Procedures.Procedure1<? super T>)```. As far as I can tell this is as a result of the same issue, and if so releasing the fix given in this issue thread in a patch would be even more helpful for me.

Otherwise, if it is a separate issue, I can create a new thread.

Thanks,
Matthew McNally

**Comment by gallandarakhneorg** [comment]
Release 0.5.8 is under progress.

**Comment by hypnobunny** [comment]
Thanks very much for this @gallandarakhneorg. :)
