### ISSUE TITLE
Build issue in the Janus Platform for Maven

### ISSUE THREAD

**Issue by tpiotrow** [sarl/sarl#721]
When I try to make the initial build with maven as per the contributing guidelines, I encounter an error in the sub-project io.janusproject.kernel. I have attached a log of my error, trimmed to relevant information.

Since the error mentioned a "No such file or directory" I ensured the directory hierarchy, the file and the access permissions are correct.
[output.txt](https://github.com/sarl/sarl/files/1241165/output.txt)

**Comment by gallandarakhneorg** [comment]
Is the file `sre/io.janusproject/io.janusproject.kernel/target/io.janusproject.kernel-0.6.0-SNAPSHOT-with-dependencies.jar` exist after the maven command has failed?

**Comment by tpiotrow** [comment]
No. The existing file(s) are **sre/io.janusproject/io.janusproject.kernel/target/io.janusproject.kernel-**2**.0.6.0-SNAPSHOT.jar

**Comment by gallandarakhneorg** [comment]
You're right. This is the good version number. I will try to reproduce this issue on my own environment.

**Comment by gallandarakhneorg** [comment]
I cannot reproduce this issue. My log shows:
```
[INFO] --- maven-jar-plugin:3.0.2:jar (default-jar) @ io.janusproject.kernel ---
[INFO] Building jar: /home/sgalland/git/sarl/sre/io.janusproject/io.janusproject.kernel/target/io.janusproject.kernel-2.0.6.0-SNAPSHOT.jar
[INFO] 
[INFO] --- maven-assembly-plugin:3.1.0:single (make-assembly) @ io.janusproject.kernel ---
[INFO] Reading assembly descriptor: with-dependencies.xml
[INFO] Building jar: /home/sgalland/git/sarl/sre/io.janusproject/io.janusproject.kernel/target/io.janusproject.kernel-2.0.6.0-SNAPSHOT-with-dependencies.jar
[INFO] 
[INFO] --- launch4j-maven-plugin:1.7.12:launch4j (generate-janus-win) @ io.janusproject.kernel ---
```

Your log shows:
```
[INFO] --- maven-jar-plugin:3.0.2:jar (default-jar) @ io.janusproject.kernel ---
[INFO] Building jar: /home/tpiotrow/workspace/sarl/sre/io.janusproject/io.janusproject.kernel/target/io.janusproject.kernel-2.0.6.0-SNAPSHOT.jar
[INFO] 
[INFO] --- maven-assembly-plugin:3.1.0:single (make-assembly) @ io.janusproject.kernel ---
[INFO] 
[INFO] --- launch4j-maven-plugin:1.7.12:launch4j (generate-janus-win) @ io.janusproject.kernel ---
```

Your maven-assembly-plugin does not log the message. Mine does. Could you re-run the Maven compilation with `-X` option and copy/paste the part of the log that is dedicated to maven-assembly-plugin?

**Comment by tpiotrow** [comment]
Here is the log. I included both maven-assembly-plugin and launch4j-maven-plugin sections.
[output2.txt](https://github.com/sarl/sarl/files/1242244/output2.txt)

**Comment by gallandarakhneorg** [comment]
According to [Issue 4 of launch4j-maven-plugin](https://github.com/lukaszlenart/launch4j-maven-plugin/issues/4), you should install the following libraries:
* zlib.i686
* ncurses-libs.i686, and
* bzip2-libs.i686

I will update the documentation accordingly.

**Comment by tpiotrow** [comment]
I followed your instructions and installed the libraries. It didn't had any effect. Then I installed launch4j as a standalone program and it solved my problem. It may not be included in some linux distributions by default. I also had to install the genisoimage program to solve a further compilation-related issue. 

Everything builds fine now. Thank you for your time and effort.
