### ISSUE TITLE
Valid combination of methods with default parameters causes Maven compilation failure

### ISSUE THREAD

**Issue by hypnobunny** [sarl/sarl#729]
Hi,

Given the following capacity:

~~~
package example

import io.sarl.lang.core.Address
import io.sarl.lang.core.Scope
import io.sarl.util.Scopes

capacity Example 
{
    def firstExampleMethod(scopeWithDefault : Scope<Address> = Scopes.<Address>allParticipants)

    def secondExampleMethod(paramWithDefault : boolean = true)
}
~~~

This capacity compiles in SARL-Eclipse with no issues. However, when using the Maven CLI compiler, the following error is produced:

~~~
[ERROR] Type mismatch: cannot convert from <null> to boolean [path/to/project/src/main/sarl/example/Example.sarl:11]
~~~

This is tested with SARL 0.5.7 and 0.5.8, both produce the error.

Cheers,
Matthew McNally

**Comment by gallandarakhneorg** [comment]
This issue could be reproduced into the testing framework with SARL 0.6.

**Comment by gallandarakhneorg** [comment]
Work-around until this issue is fixed:
```sarl
capacity Example 
{
    def firstExampleMethod(scopeWithDefault : Scope<Address>)
    def firstExampleMethod()

    def secondExampleMethod(paramWithDefault : boolean)
    def secondExampleMethod()
}
```

**Comment by gallandarakhneorg** [comment]
The issue is caused by a call to a static function into the default value of `scopeWithDefault`.
It has an impact on the validation of the paramWithDefault's default value type (the type of "null" is not detected)
It is not the expected behavior of the type resolver. See https://www.eclipse.org/forums/index.php/m/1771725/#msg_1771725.

**Comment by hypnobunny** [comment]
No worries, I have already used the workaround you suggested and it works fine. Just thought I'd better report the issue in case you hadn't seen it before!

Cheers,
Matt

**Comment by gallandarakhneorg** [comment]
Thank you. Indeed, I never encounter this issue before.
