### ISSUE TITLE
Invalid "int == AtomicInteger"

### ISSUE THREAD

**Issue by gallandarakhneorg** [sarl/sarl#764]
The following condition is always evaluted to `false`:
```sarl
var a : int = 4
var b : Integer = 4
a == b
```

**Comment by gallandarakhneorg** [comment]
Unit tests pass successfuly for:
* `int == int`
* `int == Integer`
* `Integer == int`
* `Integer == Integer`

**Comment by ngaud** [comment]
It is not exactly int == integer but int == AtomicInteger.
It is not really a bug but a behavior that could may be optimized by adding a warning.



if you have the following code :

'''
agent CounterAgent {
	[....]
	var count:AtomicInteger
	val max : Integer = 20
	[....]
	on Count {
		if (count == max) {
			[....]
		} else {
			[....]
		}
	}

	[....]
'''
You have no warning for count == max but it simply doesn't work when you launch the agent, it never stops.
The right code should be (count.get == max).

**Comment by gallandarakhneorg** [comment]
For Integer, the generated Java code is:
```java
int a = 4;
Integer b = new Integer(4);
a == b.intValue();
```

Since AtomicInteger is a Number. It should work as Integer.
The generated Java code should be also:
```java
int a = 4;
AtomicInteger b = new AtomicInteger(4);
a == b.intValue();
```

I will write unit tests for this case, and update the expression generator accordingly.

**Comment by gallandarakhneorg** [comment]
The current Java generator, inherited from Xbase generates:
```java
int a = 4;
AtomicInteger b = new AtomicInteger(4);
Objects.equal(Integer.valueIf(a), b)
```
Unfortunatelly, the `equals()` function on AtomicInteger is not defined. That's why the condition is always evaluated to false. This problem exists for all the atomic numbers.

**Comment by gallandarakhneorg** [comment]
A temporary patch will be provided into SARL.

The discussion related to the patching of Xbase could be found at: https://github.com/eclipse/xtext-extras/issues/186

**Comment by gallandarakhneorg** [comment]
Due to the discussions in https://github.com/eclipse/xtext-extras/issues/186, the `==` extension method working with `AtomicInteger` will not be part of Xbase.

The code of SARL should be rewrite accordingly, by moving the code from the "pending Xbase contribution" folder to a SARL compiler folder.
