### ISSUE TITLE
Error: Could not find or load main class io.janusproject.Boot

### ISSUE THREAD

**Issue by aminmarani** [sarl/sarl#768]
I use SARL IDE 0.7.0 version and face the "Error: Could not find or load main class io.janusproject.Boot
" error when simply run any existing examples like pingpong or holarchy. The error appears when I run holarchy.sarl or boot.sarl. Every other projects also make the same error.
I would be appreciated if you could help.
other details: 
win 10

**Comment by gallandarakhneorg** [comment]
It is fixed into Version 7.0. And, it will be available soon within the product.
