### ISSUE TITLE
SARL Acronym meaning

### ISSUE THREAD

**Issue by gallandarakhneorg** [sarl/sarl#769]
I have more and more people asking me that is the meaning of "SARL".

I know we have not yet decided of this meaning. I would like to propose a contest on Facebook and Google Group for giving the opportunity to the community to propose a meaning.

To be accepted, the proposed meaning should be put as a comment of this issue, in order to keep track of the initial proposer.

The core developers of SARL (@gallandarakhneorg, @ngaud , @srodriguez) will decide of the best proposal.

You could also vote for a proposal by adding a :+1: or :-1:  or :heart: (multiple votes are accepted)

Deadline: Release of Version 1.0.0.

**Comment by gallandarakhneorg** [comment]
"SARL Agent-pRogramming Language" => recursive definition as GNU.

**Comment by gallandarakhneorg** [comment]
"general purpoSe Agent-pRogramming Language"

**Comment by grivadera** [comment]
Wouldn't be appropiate to include Holonic in the name? :). Something like General Holonic Agent Development System..
Regards, 
Gustavo

**Comment by gallandarakhneorg** [comment]
Dear @grivadera.
At the birth date of SARL, we have decided to use the "agent" term in order to cover the holonic agents and not-holonic agents. Nevertheless, you're right to mention  that holon support is a key feature of SARL.

Possibility in my mind are:
"SARL holon and Agent-pRogramming Language"

**Comment by gallandarakhneorg** [comment]
Something coming from early discussions between the core developers:
"Social Agent and Rational Language"

**Comment by grivadera** [comment]
I agree with Nicolas, but is a Language used by a Social Agent, or a Language for constructing Social Agents?, it is subtle, and perhaps I am going too far...

**Comment by gallandarakhneorg** [comment]
I think both: SARL may be used for programming a social agent, and an agent (not written with SARL) may call functions or features written with SARL; my two cents.

**Comment by hypnobunny** [comment]
My vote is towards **S**ocial **A**gent **R**eactive **L**anguage. I feel that SARL's main benefit is its highly concurrent, event-driven architecture ... it is a prime example of integration of agent-oriented concepts and a strong reactive programming model.

**Comment by ngaud** [comment]
OK with Social Agent Reactive Language

**Comment by Aethor** [comment]
What about "SARL Agent Reactive Language", to keep the recursive definition

**Comment by srodriguez** [comment]
At the time we talked about Social Agent Representation Language as well as Reactive and Rational. We never finally decided the "R". I really like having some recursive definition.

**Comment by andresiraola** [comment]
My two cents .. Simple Agents Relationship Lexicon

**Comment by gallandarakhneorg** [comment]
Dear @andresiraola. "Lexicon" is not appropriate because a programming language is defined by its vocabulary (lexicon, set of lexemes), its grammar (syntax), and its meaning (semantic). SARL is a language, not only a lexicon.
Additionally, I think SARL is not so "Simple" to have this adjective in its name :smiley:.

**Comment by ssardina** [comment]
I would vote for "SARL Agent Reactive Language". Agent, Reactive, and Language are very adequate (even  necessary?) terms to describe SARL. 

So this leaves just the "S". Social would be OK, but is more up to interpretation (it's not that the focus is in social aspects, like speech acts, organizations, norms, etc). By doing "SARL", the recursive definition is achieved, which is nice. Unless a more adequate interpretation for the "S" is found (I cannot think of one), I would opt for "SARL" :-)

**Comment by gallandarakhneorg** [comment]
Dear Sebastian. Since agents are social by definition, I think we could skip "Social" and stay on "SARL". Additionally, I prefer the recursive definition :smile:

**Comment by WeiLunLa** [comment]
How about "S" for Software?

**Comment by gallandarakhneorg** [comment]
Dear @WeiLunLa. "Software Agent" is too restrictive from my point of view. What about "Robotic Agent"?I'm using SARL for implementing drone algorithms for example. My two cents.

**Comment by gallandarakhneorg** [comment]
After querying ChatGPT, it proposes the relevant following meanings for SARL:

1. Software Agent and Robotics Language
2. Synthetic Agent and Robotics Language
3. Software Agent Reasoning Language

I vote for 1 that seems to cover a large part of the past and current applications of SARL.

**Comment by srodriguez** [comment]
There is no need to impose any meaning.
