### ISSUE TITLE
using hadoop in sarl + calling sarl classes in java

### ISSUE THREAD

**Issue by aminmarani** [sarl/sarl#774]
I have 2 questions that cannot get answers on the net.
1-How can one call sarl projects and classes like pingpong project in java classes to run using java class 
2-Wanna use hadoop in order to implement big data usign sarl, how can I use hadoop in sarl projects, again through a java class.(use sarl agents in java class and relate it to hadoop to run on hadoop)

**Comment by gallandarakhneorg** [comment]
Using hadoop from a SARL program is very easy. You have to include your hadoop Java library in the SARL imports and use the imported type within the SARL program.

Launching SARL agents from hadoop should be done by calling the SARL booting API. The following page provides simple examples: http://www.sarl.io/docs/official/gettingstarted/RunSARLAgentJava.html

**Comment by aminmarani** [comment]
I think my ambiguity of using hadoop and sarl is because of I do not know how to call sarl agent in a java class. Actually, I have read the page you introduced in your reply but I cannot get it to work!
Here are some details about my failure try:
-eclpse_sarl(0.6.0)
-Unfortunately I could not use exact codes in "http://www.sarl.io/docs/official/gettingstarted/RunSARLAgentJava.html" because does not seem to be written in java and eclipse failed to compile them.
-I changed them in this manner:
               SREBootstrap bb =  SRE.getBootstrap();
		UUID a1 = new UUID(10l,10l);
		Auctioneer ac = new Auctioneer(a1, a1);
		bb.startAgent(ac,null);
but it says startAgent only recieves agent extended classes.

-sorry I am a little novice in sarl and janus related information.

**Comment by gallandarakhneorg** [comment]
You cannot create an instance of a SARL agent by yourself.
Only the run-time platform is allowed to do that.
The Java code may be:
```java
SREBootstrap bb = SRE.getBootstrap();
UUID a1 = bb.startAgent(Auctioneer.class);
```

Additionally, I do not recommend to create an agent with a specific constructor. It means that th constructor called by  `new Auctioneer(a1, a1)` should not exist.

The SARL code of your Auctioneer should start with:
```sarl
agent Auctioneer {
    on Initialize {
        var initializationParameters = occurrence.parameters
    }
}
```

In order to have the bootstrap working, you must put the Janus Jar file within the classpath of your application.

**Comment by aminmarani** [comment]
tnx for helping. i used what u said:
SREBootstrap bb = SRE.getBootstrap();
		try {
			UUID a1 = bb.startAgent(Auctioneer.class);
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

but there was an exception said:
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/cli/ParseException
	at io.janusproject.Bootstrap.startAgent(Bootstrap.java:59)
	at Main.main(Main.java:23)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.cli.ParseException
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 2 more

* janus jar file was added to build path

**Comment by gallandarakhneorg** [comment]
Are you using Maven for compiling your project ?
If yes, add the following dependnecy within your project:
```
<dependency>
          <groupId>io.janusproject</groupId>
          <artifactId>io.janusproject.kernel</artifactId>
          <version>2.0.6.0</version>
</dependency>
```

If you are not using Maven, you have to download the Janus Jar file that contains all the dependencies, and add this Jar file within your classpath. See the section "Download the Java Library for Janus Run-time Environment" from the download page.

Please double check if your are using the correct Jar file, and come back to me.

**Comment by aminmarani** [comment]
Tnx for additional information and helping me our.
I am working on holony+hadoop project in order to make a recommender  system, I wonder if I could ask more question about hadoop and sarl combination just to know fundamental steps.

**Comment by gallandarakhneorg** [comment]
You're welcome to ask you questions on the SARL google group, that is a better place for discussions: https://groups.google.com/forum/#!forum/sarl
