### ISSUE TITLE
Mauvaise erreur compilateur

### ISSUE THREAD

**Issue by PRuffy** [sarl/sarl#792]
Le code ci-dessous

`override translate(vector : Tuple2f<?>) : MotionHull2f {
		return new MotionHull2f(new Point2f(this.start.x + vector.x, this.start.y + vector.y), this.direction.clone,this.size)
	}`

Provoque l'erreur suivante : 
`io.sarl.lang.sarl.impl.SarlClassImplCustom cannot be cast to org.eclipse.xtend.core.xtend.XtendFunction - See error log for details` 

Alors que le problème vient de l'absence de la fonction clone() dans la classe associer à la variable direction.

**Comment by gallandarakhneorg** [comment]
A temporary fix is: uncheck the "Generate @Pure annotations" within the general preferences of the SARL compiler.
