### ISSUE TITLE
Impossible d'assigner une valeur négative à une variable short

### ISSUE THREAD

**Issue by Notmoo** [sarl/sarl#793]
# Informations

* OS : Windows 10 Pro
* SARL : version 0.6.1
* Langue : EN

# Description

En SARL, tenter d'assigner une valeur négative à une variable short est considéré comme une erreur, avec ou sans le typecast (voir ci-contre) : 
____
![sans titre2](https://user-images.githubusercontent.com/9350272/33724423-af8b0c2a-db6f-11e7-8887-a6ebf3dec230.png)
____
![sans titre3](https://user-images.githubusercontent.com/9350272/33725296-0442d5f2-db72-11e7-8fde-38abdd8603de.png)
____

Cependant, tenter d'assigner une valeur positive ne provoque pas cette erreur dès lors que le typecasting est utilisé : 

____
![sans titre4](https://user-images.githubusercontent.com/9350272/33725352-2ebce3ae-db72-11e7-8a7a-7643ea1df48c.png)
____
![sans titre](https://user-images.githubusercontent.com/9350272/33724422-af7372ea-db6f-11e7-8b32-e2ca906b7264.png)
____

# Résultat attendu

Logiquement, on s'attendrait à pouvoir assigner une valeur négative à une variable short de la même manière qu'une valeur positive, indépendamment de la méthode (typecast, etc...).

# Reproduction de l'erreur

*Reproduction testée sur une seule machine, spécificités décrites dans la partie "Informations"*

1. créer une capacité avec une méthode et un skill qui l'implémente
1. déclarer une variable de type short en assignant une valeur négative *(voir images dans la partie "Description")*

**Comment by gallandarakhneorg** [comment]
The use cases 1, 3 and 4 provides the expected results, according to the definition of the expression statement within the Xbase project.

Use case 2 should pass and not generate an error. It should be fixed within the Xbase library.

**Comment by gallandarakhneorg** [comment]
See Xbase issue [68](https://github.com/eclipse/xtext-lib/issues/68) to follow up.

**Comment by gallandarakhneorg** [comment]
To solve your problem, until the fix is released, you haveto use:
```
var temp_node_id : short = (-1) as short
```
