### ISSUE TITLE
Janus is not able to match the corresponding agent name to the existing class.

### ISSUE THREAD

**Issue by Talxolenia** [sarl/sarl#811]
#### Issue description

on windows 7 64-bit command line, 
when trying to lunch an agent with CMD
Janus is not able to match the corresponding agent name to the existing class.

#### Steps to reproduce the issue

1. Create SARL project with eclipse-sarl.exe (name the project "test").
2. In src/main/sarl folder add a new agent (name the agent jack).
3. Compile the project.
4. open the physical path of src\main\generated-sources\ 
(ex. D:\sarl\src\main\generated-sources\sarl\test\).
5. lunch the CMD by holding shift key and pressing right click on the background of the folder.
6. Type "janus test.jack" & press enter.

#### What's the expected result?

-Janus should start and create the Agent jack.

#### What's the actual result?

-The agent is not starting, information message is telling
"The fully qualified name 'test.jack' does not correspond to an existing class.
The default class path is:
C:\SARL\janus.exe"

#### Additional details / screenshot

- JANUS version: 2.0.6.1
- SARL version: 0.6.1
- SARL compiler:
  - [x] Eclipse compiler without Maven
  - [ ] Eclipse compiler with Maven
  - [ ] Maven compiler on the command line
  - [ ] sarlc compiler
- Java JDK version (1.8.0_161 Java HotSpot(TM) 64-bit server VM):
- Operating System:
  - [ ] Linux 64bits
  - [ ] Linux 32bits
  - [x] Windows 64bits
  - [ ] Windows 32bits
  - [ ] MacOS 64bits
- ![Screenshot]()
![image](https://user-images.githubusercontent.com/24508169/36263039-9cf99fd2-1282-11e8-9a7e-6b1a187fb5c9.png)

**Comment by gallandarakhneorg** [comment]
Could you give the output of the command `dir *.class`.

**Comment by Talxolenia** [comment]
![image](https://user-images.githubusercontent.com/24508169/36300830-235648c0-131c-11e8-87a5-eaa92f89aa85.png)

**Comment by gallandarakhneorg** [comment]
Please not that the Janus command runs the "class" files that are the results of the compilation of the SARL program. Janus is not working as a script language such as Python or Ruby, which are taking the python and ruby source code as inputs. We are following the principles of the Java tools: one tool for compiling (Eclipse or sarlc), and one tool for running (janus).
However, this issue is now fixed. And, janus command line works as expected in the version 0.7 of SARL.
