### ISSUE TITLE
Slow spawning of Agents

### ISSUE THREAD

**Issue by GlennCich** [sarl/sarl#814]
#### Issue description
Hi,

yesterday I attempted to launch 5000 agents. This succeeded without any problem, however it took almost 2 hours to do this. Is this normal? Or can I speed up this process?

The launching is something like:
```
for (agent : agents)
{
  if (agent = A)
  {
    // get a lot of attributes
    spawn(A, /* a lot of attributes */)
  }
  else if (agent = B)
  {
    // get a lot of attributes
    spawn(B, /* a lot of attributes */)
  }
}
```

#### Additional details / screenshot

- SARL version: 0.7
- SARL compiler:
  - [x] Eclipse compiler without Maven
  - [ ] Eclipse compiler with Maven
  - [ ] Maven compiler on the command line
  - [ ] sarlc compiler
- Java JDK version (with the manufacturer name):
- Operating System:
  - [x] Linux 64bits
  - [ ] Linux 32bits
  - [ ] Windows 64bits
  - [ ] Windows 32bits
  - [ ] MacOS 64bits

**Comment by gallandarakhneorg** [comment]
Possible solution could be found in #751, and should be validated by @srodriguez.

**Comment by gallandarakhneorg** [comment]
Issue #751 enables to choose between the injection and not injection for the creation of the agent. By default, agents are not any more injected. It may improve the spawning of the agents, and injection is not usually used when creating an agent.

**Comment by gallandarakhneorg** [comment]
New spawning process is implemented into the new SRE. It includes a no-injection based mechanism and faster ID computation.
