### ISSUE TITLE
SARL skill wizard bug

### ISSUE THREAD

**Issue by GlennCich** [sarl/sarl#823]
#### Issue description
When creating a skill with the wizards, an error occurred. This happens sometimes...

See the log file, bug happened around 09:19

#### Additional details / screenshot

- SARL version:
- SARL compiler:
  - [x] Eclipse compiler without Maven
  - [ ] Eclipse compiler with Maven
  - [ ] Maven compiler on the command line
  - [ ] sarlc compiler
- Java JDK version (with the manufacturer name):
- Operating System:
  - [x] Linux 64bits
  - [ ] Linux 32bits
  - [ ] Windows 64bits
  - [ ] Windows 32bits
  - [ ] MacOS 64bits
- ![Screenshot](
![bugcreatingskill](https://user-images.githubusercontent.com/17176275/37452751-d2351762-2835-11e8-8e31-b2b9e42d6f11.png)
[bug.log](https://github.com/sarl/sarl/files/1814568/bug.log)

)

**Comment by gallandarakhneorg** [comment]
Could you provide us the code of the capacity to be implemented because it is not shown on the picture.

**Comment by GlennCich** [comment]
'''
/** 
 * 
 */
package be.uhasselt.imob.smartpt.application.inhabitants.^capacity.generic

/** 
 * @author glenn
 * 
 */
capacity ResultsWriterCapacity 
{
	def logResults() : void
}
'''
