### ISSUE TITLE
Erreur lors de la compilation du projet Maven sarl

### ISSUE THREAD

**Issue by beta-ray70** [sarl/sarl#827]
#### Issue description
Impossible de compiler un projet sarl avec un maven.

Je souhaitais utiliser maven pour le projet d'IA51 en Sarl.

Ainsi j'ai suivi ce tutoriel : http://www.sarl.io/docs/official/gettingstarted/CreateFirstProject.html#2-create-a-sarl-project-with-maven

J'ai ainsi obtenu le fichier pom présent au sein de cette issue.

J'obtiens l'erreur ci-dessous, lorsque je souhaite compiler le projet avec la commande mvn install ou mvn compile : 

[INFO] --- sarl-maven-plugin:0.7.0:compile (default-compile) @ toto ---
[INFO] Checking if the SARL library is present, and is compliant with version 0.7.0 [0.7.0, 0.8.0)
[INFO] Detected SARL version in dependencies: 0.7.0
[INFO] Checking versions of the artifacts
[INFO] Starting SARL compiler
[INFO] Generating and inferring the target model(s)
[INFO] Validating the SARL source files
[INFO] Creating the target model file(s) into the folder C:\Users\Julien Barbier\Downloads\io.sarl.lang.updatesite-0.7.0-win32.win32.x86_64\workspace\toto\src\main\generated-sources\sarl
[INFO] Compiling the generated Java source file(s)
[ERROR] Unrecognized option : C:\Users\Julien Barbier\Downloads\io.sarl.lang.updatesite-0.7.0-win32.win32.x86_64\workspace\toto\src\main\generated-sources\sarl
[ERROR]

#### Steps to reproduce the issue

1.  Créer un projet SARL maven depuis l'IDE Sarl
2.  Modifier le maven pour ajouter les dépendances comme précisé dans le tutoriel SARL
3. Compiler le projet avec les commandes maven install ou maven compile

#### What's the expected result?

- Pas d'erreur à la compilation lors de la compilation du SARL

#### What's the actual result?

- [INFO] --- sarl-maven-plugin:0.7.0:compile (default-compile) @ toto ---
[INFO] Checking if the SARL library is present, and is compliant with version 0.7.0 [0.7.0, 0.8.0)
[INFO] Detected SARL version in dependencies: 0.7.0
[INFO] Checking versions of the artifacts
[INFO] Starting SARL compiler
[INFO] Generating and inferring the target model(s)
[INFO] Validating the SARL source files
[INFO] Creating the target model file(s) into the folder C:\Users\Julien Barbier\Downloads\io.sarl.lang.updatesite-0.7.0-win32.win32.x86_64\workspace\toto\src\main\generated-sources\sarl
[INFO] Compiling the generated Java source file(s)
[ERROR] Unrecognized option : C:\Users\Julien Barbier\Downloads\io.sarl.lang.updatesite-0.7.0-win32.win32.x86_64\workspace\toto\src\main\generated-sources\sarl

#### Additional details / screenshot

- SARL version: 0.7.0 (présent aussi dans la version 0.7.1)
- SARL compiler:
  - [] Eclipse compiler without Maven
  - [] Eclipse compiler with Maven
  - [x] Maven compiler on the command line
  - [ ] sarlc compiler
- Java JDK version (with the manufacturer name): 1.8.0_161 (JDK provenant d'Oracle)
- Operating System:
  - [] Linux 64bits
  - [ ] Linux 32bits
  - [X ] Windows 64bits
  - [ ] Windows 32bits
  - [ ] MacOS 64bits
- ![Screenshot]()
[pom.zip](https://github.com/sarl/sarl/files/1853346/pom.zip)

**Comment by gallandarakhneorg** [comment]
J'ai modifié le fichier `pom.xml` pour utiliser la bonne version de SARL:
```xml
<sarl.version>0.7.1</sarl.version>
```
Je n'obtiens pas d'erreur avec un code SARL basique.
Avez-vous dans votre projet un code SARL particulier qui pourrait provoquer l'erreur de compilation?

**Comment by gallandarakhneorg** [comment]
Please run maven with `mvn -X clean install` and provide the log.

**Comment by beta-ray70** [comment]
[log.txt](https://github.com/sarl/sarl/files/1859587/log.txt)
Voilà le fichier de log comme demandé.

**Comment by beta-ray70** [comment]
[toto.zip](https://github.com/sarl/sarl/files/1868598/toto.zip)
 Veuillez trouver le projet ne compilant pas ici même.

**Comment by gallandarakhneorg** [comment]
Release [0.7.2](http://www.sarl.io/download/changes_0.7.2.html) will be available soon on the Maven central server. It includes the patch for this issue.

**Comment by pinam45** [comment]
The project still doesn't compile on my computer with SARL 0.7.2.

project: [toto.zip](https://github.com/sarl/sarl/files/1872722/toto.zip)
``mvn -X clean install`` log: [log.txt](https://github.com/sarl/sarl/files/1872728/log.txt)

system info:
```
$ uname -a                                                                                                                                                                                                                           
Linux 4.15.0-2-amd64 #1 SMP Debian 4.15.11-1 (2018-03-20) x86_64 GNU/Linux

$ mvn -v                                                                                                                                                                                                                             [2][20:03]
Apache Maven 3.5.2
Maven home: /usr/share/maven
Java version: 9.0.4, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-9-openjdk-amd64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.15.0-2-amd64", arch: "amd64", family: "unix"
```

**Comment by gallandarakhneorg** [comment]
According to your logs, there is a problem with the version of the JDK that is used for compiling the unit tests. Log indicates that version 1.5 is used.

Please update your `pom.xml` file with:
```xml
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>4.12</version>
      <scope>test</scope>
    </dependency>
```

If it does not works, force the version of the Java compiler:
```xml
<properties>
    <maven.compiler.source>1.5</maven.compiler.source>
    <maven.compiler.target>1.5</maven.compiler.target>
</properties>
```

**Comment by pinam45** [comment]
It still doesn't work with junit 4.12 and the compiler version forced to 1.8 but I think the problem is related to Java-9.
```
$ java -version                                                                                                                                                                                                                      
openjdk version "9.0.4"
OpenJDK Runtime Environment (build 9.0.4+12-Debian-4)
OpenJDK 64-Bit Server VM (build 9.0.4+12-Debian-4, mixed mode)

```

Under Windows it works with Java-8, not tested with Java-9.

**Comment by gallandarakhneorg** [comment]
Do not use Java 9. It is incompatible with a part of the libraries within the SARL product.
Downgrade to Java 8 and try again.
If it does not work, please come friday in order to let me test the things on your laptop.
