### ISSUE TITLE
Unexpected ERROR at Validating the SARL source files

### ISSUE THREAD

**Issue by ssardina** [sarl/sarl#847]
**Describe the bug**

Get this error:

```
1    [main] ERROR text.validation.CompositeEValidator  - Error executing EValidator
org.eclipse.emf.common.util.BasicEList$BasicIndexOutOfBoundsException: index=2, size=2

```
where I should not. I have an equivalent code that works well with no error.

**To Reproduce**

This code:

```
	on AgentSpawned {
		info("Agent {0} of type {1} has been created successfully and is now alive!",
			occurrence.agentIdentifiers, occurrence.agentType)
	}

```

gives this error:

```
[INFO] Validating the SARL source files
1    [main] ERROR text.validation.CompositeEValidator  - Error executing EValidator
org.eclipse.emf.common.util.BasicEList$BasicIndexOutOfBoundsException: index=2, size=2
	at org.eclipse.emf.common.util.BasicEList.get(BasicEList.java:346)
	at io.sarl.lang.validation.SARLValidator.checkUnmodifiableEventAccess(SARLValidator.java:2282)
	at io.sarl.lang.validation.SARLValidator.checkUnmodifiableEventAccess(SARLValidator.java:2334)
```

but this codes works well:

```
	on AgentSpawned {
		val agent_ids = occurrence.agentIdentifiers
		val agent_type = occurrence.agentType
		info("An Agent {0} (of type: {1}) has been created successfully and is now alive!", agent_ids, agent_type)
	}

```

**Expected behavior**

No error.

**Screenshots**

**System configuration:**
-- SARL version:	0.7.2
-- SARL compiler:	
-  - [] Eclipse compiler without Maven	
-  - [ ] Eclipse compiler with Maven	
-  - [X ] Maven compiler on the command line	
-  - [ ] sarlc compiler	
-- Java JDK version (with the manufacturer name):	
-- Operating System:	
-  - [x] Linux 64bits	
-  - [ ] Linux 32bits	
-  - [ ] Windows 64bits	
-  - [ ] Windows 32bits	
-  - [ ] MacOS 64bits

**Comment by ssardina** [comment]
awesome, that was quick, thanks!

**Comment by gallandarakhneorg** [comment]
You're welcome. When it is easy to fix, it should be quick :-)

**Comment by ssardina** [comment]
Good. Glad it helped to get rid of one (small) glitch.
