### ISSUE TITLE
occurrence.fromMe in event AgentSpawned

### ISSUE THREAD

**Issue by ssardina** [sarl/sarl#849]
**Describe the bug**

Presumably, occurrence.fromMe states whether the event was emitted by that agent itself, i.e., the one handling it with an on rule behavior.

However, when it comes to event AgentSpawned, it appears that occurrence.fromMe states whether the agent spawned was indeed spawned by the agent handling the event!

**To Reproduce**

An agent X spawns various agents in its Initialize and has this behavior:

```
	on AgentSpawned  {
		if (occurrence.fromMe) {
     		info("Agent has spawned: {0} (THIS IS ME!!!)", occurrence.agentIdentifiers)
   		} else {
			info("Agent has spawned: {0}", occurrence.agentIdentifiers)
   		}
	}

```

And I get:

```
INFO, 10:36:46pm, AGENT-66a8ad68-12e1-4f48-81b8-0e3ca69e7e5e] Agent has spawned: [66a8ad68-12e1-4f48-81b8-0e3ca69e7e5e]
[INFO, 10:36:46pm, AGENT-66a8ad68-12e1-4f48-81b8-0e3ca69e7e5e] Agent has spawned: [a2ed0355-4cd4-4616-b5a5-4f403ba70f02] (THIS IS ME!!!)
[INFO, 10:36:46pm, AGENT-66a8ad68-12e1-4f48-81b8-0e3ca69e7e5e] Agent has spawned: [147be055-ecbb-4380-850e-a5c277dfa8df] (THIS IS ME!!!)
[INFO, 10:36:46pm, AGENT-66a8ad68-12e1-4f48-81b8-0e3ca69e7e5e] Agent has spawned: [23b8de77-8cac-4dac-91a1-6d254057f59b] (THIS IS ME!!!)
[INFO, 10:36:46pm, AGENT-66a8ad68-12e1-4f48-81b8-0e3ca69e7e5e] Agent has spawned: [553f6404-7e0d-4e9a-b24b-03983278947f] (THIS IS ME!!!)
[INFO, 10:36:46pm, AGENT-66a8ad68-12e1-4f48-81b8-0e3ca69e7e5e] Agent has spawned: [0234e0d9-a439-4734-b938-f776541815ed] (THIS IS ME!!!)

```

This is self-explanatory, just look at where **THIS IS ME!!!** text shows up

**Expected behavior**

I would expect occurrence.fromMe still stating whether I generated the event.

**Screenshots**

**System configuration:**
-- SARL version:	0.7.2
-- SARL compiler:	
-  - [] Eclipse compiler without Maven	
-  - [X] Eclipse compiler with Maven	
-  - [X ] Maven compiler on the command line	
-  - [ ] sarlc compiler	
-- Java JDK version (with the manufacturer name): Sun 1.8	
-- Operating System:	
-  - [x] Linux 64bits	
-  - [ ] Linux 32bits	
-  - [ ] Windows 64bits	
-  - [ ] Windows 32bits	
-  - [ ] MacOS 64bits	

**Additional context**

**Comment by gallandarakhneorg** [comment]
Fixed in #848
