### ISSUE TITLE
Unable to launch a SARL agent from CLI with maven

### ISSUE THREAD

**Issue by RyuzakiKK** [sarl/sarl#853]
**Describe the bug**
Trying to launch a SARL agent from CLI with maven doesn't work.
I used `mvn exec:java -Dexec.mainClass="io.janusproject.Boot" -Dexec.args=com.MyAgent` but I get the error: "The fully qualified name [...] does not correspond to an existing class"

This seems to be a regression with SARL 0.7.2, because with SARL 0.6.1 it works as expected.

**To Reproduce**
1. Clone this project https://github.com/sarl/sarl-demos/tree/master/src/main/sarl/io/sarl/demos/pingpong/subcontext
2. Edit the [pom.xml](https://github.com/sarl/sarl-demos/blob/master/pom.xml) with
`<sarl.version>0.7.2</sarl.version>` and `<janus.version.range>2.0.7.2</janus.version.range>`
3. execute `mvn clean package`
4. execute `mvn exec:java -Dexec.mainClass=io.janusproject.Boot -Dexec.args=io.sarl.demos.pingpong.subcontext.BootAgent`
4. See the error `The fully qualified name [...] does not correspond to an existing class`

**Expected behavior**
A successfully execution of the Agent was expected.

**System configuration:**
- SARL version:	0.7.2
- SARL compiler:	
  - [ ] Eclipse compiler without Maven	
  - [ ] Eclipse compiler with Maven	
  - [x] Maven compiler on the command line	
  - [ ] sarlc compiler	
- Java JDK version (with the manufacturer name):	jdk8-openjdk 8.u181
- Operating System:	
  - [x] Linux 64bits	
  - [ ] Linux 32bits	
  - [ ] Windows 64bits	
  - [ ] Windows 32bits	
  - [ ] MacOS 64bits

**Comment by gallandarakhneorg** [comment]
Please not that https://github.com/sarl/sarl-demos/ is a repository that is no more maintened. It is provided for history.

The most recent codes of the demos are embedded into the SARL Development Environment.

For creating a project with the code of a demo:
* Menu File > New > Examples
* In the wizard, select the demo to open.
* Close the wizard.

**Comment by gallandarakhneorg** [comment]
This is more problem related to the Maven Exec plugin than to SARL. I can run the demo with the following command line:
```bash
mvn exec:exec -Dexec.executable=java -Dexec.args="-cp %classpath io.janusproject.Boot io.sarl.examples.pingpongspace.BootAgent"
```

The `%classpath` is dynamically replaced by the project's classpath.
