### ISSUE TITLE
Spawning an agent never returns in 0.8.1 

### ISSUE THREAD

**Issue by ssardina** [sarl/sarl#866]
**Describe the bug**

This line never returns (all arguments have been computed well):

`val UUID = spawn(SWISingleFullAgent, teamManager, TimestampedDir.getDir())
`

**To Reproduce**

A bit hard to explain here but:

1. Clone this repo: <https://bitbucket.org/ssardina-research/sarl-agtcity-base>
2. Run `mvn clean package`
3. Run `mvn exec:java`
4. Select option 4: `BootMultiSWIAgents`

Such agent runs this code which gets stuck at spawning:

```
                debug("Starting to spawn the manager agents")
		noToSpawn = teamManagers.size
		noSpawn = 0
		teamManagers.forEach([ teamManager : PlayersManager |
			debug("About to spawn team manager **{0}**", teamManager.myName)
			val UUID = spawn(SWISingleFullAgent, teamManager, TimestampedDir.getDir())
			debug("\t SARL agent for team manager **{0}** spawn...", teamManager.myName)
			synchronized (agentsToComplete) {
				agentsToComplete.add(UUID)
			}
		])
```

This used to work perfectly with 0.7.2

A bit of dubugging in ECLIPSE tells me execution gets stuck in `this.spawnService.spawn(...)`, line 102 in LifecycleSkill; all arguments have been computed well.

**Expected behavior**

Should just spawn the agents as 0.7.2 did.

**Screenshots**

![image](https://user-images.githubusercontent.com/2368384/46240975-c2a69880-c3f2-11e8-8b23-0871dcc799cb.png)

**System configuration:**
-- SARL version:	0.8.1
-- SARL compiler:	
-  - [X] Eclipse compiler without Maven	
-  - [ ] Eclipse compiler with Maven	
-  - [ X] Maven compiler on the command line	
-  - [ ] sarlc compiler	
-- Java JDK version (with the manufacturer name): 1.8 Sun	
-- Operating System:	
-  - [x] Linux 64bits	
-  - [ ] Linux 32bits	
-  - [ ] Windows 64bits	
-  - [ ] Windows 32bits	
-  - [ ] MacOS 64bits	

**Additional context**

**Comment by gallandarakhneorg** [comment]
See Commit 658bd4628b09afcb400e31777299ee79b2441c10
