### ISSUE TITLE
Invalid it support in serializable scopes (lambda)

### ISSUE THREAD

**Issue by YannPoncet** [sarl/sarl#899]
Let:
```sarl
on Initialize {
	loggingName = "Jean1"
	Agent2.spawn
	var id = Agent3.spawn
	emit(new Hello, [elt | elt.UUID == id])
	new Hello().emit[UUID == id]
	killMe
}
```

The code generates the Java problem: ` it cannot be resolved`

**Comment by gallandarakhneorg** [comment]
This is an issue into the Java code generator.
A quick fix into your code (before the bug is really fixed into the SARL compiler) is to replace `[UUID == id]` by `[it.UUID == id]`.
