### ISSUE TITLE
Invalid log4j module version when using the SARL Maven plugin

### ISSUE THREAD

**Issue by RodolphePonthon** [sarl/sarl#913]
When compiling a basic Maven-SARL project, Maven complains about an invalid version of the log4j module and proposes to add the configuration below into the `pom.xml`:
```
<dependencyManagement>
	<dependencies>
		<dependency>
			<groupId>log4j</groupId>
			<artifactId>log4j</artifactId>
			<version>1.2.17</version>
		</dependency>
	</dependencies>
</dependencyManagement>
```

**Comment by gallandarakhneorg** [comment]
I cannot reproduce this issue on my environment.

Could you send to me a zip file of your project that is failing?

Also, could you confirm the versions of the Java JDK and SARL.
