### ISSUE TITLE
SARL compiler couldn't be executed on the JDK version 11. Please use the JDK between 1.8 and 1.8.

### ISSUE THREAD

**Issue by alexandrelombard** [sarl/sarl#940]
**Describe the bug**

The message "SARL compiler couldn't be executed on the JDK version 11. Please use the JDK between 1.8 and 1.8." appears on the package name of all classes with Eclipse SARL 0.10.0 (Build id: 20191007122655 (2019-10-07)). The name of the package is underlined in red.

On the computer both JRE exists, but only the 1.8 is selected in the settings.

Even though there is this error message, the project is building and working fine.

**To Reproduce**

Not clearly identified. It happens when opening the following project:

https://github.com/alexandrelombard/sarl-airsim-interface

**Expected behavior**

No error message.

**Screenshots**

![image](https://user-images.githubusercontent.com/22587364/66573181-8c0d6d00-eb72-11e9-94d7-45e843ee5b2d.png)

The message appears when the cursor is over the package line, but it disappeared when the screenshots were taken.

![image](https://user-images.githubusercontent.com/22587364/66573498-10f88680-eb73-11e9-96b3-d60933c49d4c.png)

![image](https://user-images.githubusercontent.com/22587364/66573551-27064700-eb73-11e9-8a94-5ae3fbdc3fb2.png)

**System configuration:**
-- SARL version:	0.10.0
-- SARL compiler:	
-  - [ ] Eclipse compiler without Maven	
-  - [x] Eclipse compiler with Maven	
-  - [ ] Maven compiler on the command line	
-  - [ ] sarlc compiler	
-- Java JDK version (with the manufacturer name): 1.8 (OpenJDK)	
-- Operating System:	
-  - [x] Linux 64bits	
-  - [ ] Linux 32bits	
-  - [ ] Windows 64bits	
-  - [ ] Windows 32bits	
-  - [ ] MacOS 64bits	

**Additional context**
-

**Comment by gallandarakhneorg** [comment]
In related with Issue #897, we could remove the check of the JDK version and try to use SARL product with Java 11.

**Comment by gallandarakhneorg** [comment]
Please reopen the issue if the JDK that is running your SARL product is 1.8.

**Comment by alexandrelombard** [comment]
> What is the value of the variable `java.runtime.version`?
> 
> It could be obtained with:
> 
> * Menu Help
> * Item "About"
> * Button "Details"
> * Tab "Configuration"
> * Scroll until the variable is displayed
> 
> Indeed, the message is output because of the compiler's execution environment.
> In this case, the JDK to consider is the one that is running Eclipse, and it may be different than the one used as dependency of the compiled project.
> 
> I suspect this variable to show up the version 11 of Java.
> 
> On my system, Eclipse SARL is runing with JDK 1.8 and everything is compiled as expected.

Indeed, Java 11 version is used to run the Eclipse SARL product. It's not used for compiling the project and running it, so that's why everything is working fine even if there is this error message.
So, indeed I guess removing the check of the JDK version would solve it.

**Comment by gallandarakhneorg** [comment]
I agree but before, we need to test more in details in JDK 11 could be used for running the SARL Eclipse IDE and the SARL applications.
We need to keep the compilation of the SARL project itself in JDK 1.8 in order to provide class files that cold be used in both the LTS JDK (1.8 and 11).
I propose to push up Issue #897 in order to solve this issue as fast as possible.
