### ISSUE TITLE
System Events (MemberJoined, ContextJoined, etc) documentation mentions that impacted agents doesn't receive the event but it receives it 

### ISSUE THREAD

**Issue by ngaud** [sarl/sarl#941]
System Events (MemberJoined, ContextJoined, etc) documentation mentions that impacted agents doesn't receive the event but this agent receives it. The best proof is the Helloworld example with a single agent receiving MemberJoined, ContextJoined, etc.

Either we change the documentation or we scope every single event emission.

**Comment by gallandarakhneorg** [comment]
See Issue #72.
