### ISSUE TITLE
Error while launching two or more SARL/Janus instances.

### ISSUE THREAD

**Issue by dlizondo** [sarl/sarl#957]
**Bug description**
Error while launching two separate instances of SARL/Janus with *SARL 0.10.0* from the generated jar file in command-line. I used a simple example of a sender/receiver message, just like the ping-pong to test agent distribution. It seems that the two kernels found each other, but the second instance crash after that, showing an error of *ZeroMQNetworkService*.
I have to clarify that this is a bug that is not present in *SARL 0.9.0*. **The same example executed in SARL 0.9.0 runs perfectly.**

**To Reproduce**
1. Compile jar from command-line with maven. POM configure to generate jar with dependencies.
2. Run the app with the first agent: java -jar app-with-dependencies.jar mySenderAgent
3. Run the app with the second agent:  java -jar app-with-dependencies.jar myReceiverAgent

[INFORMACIÓN, 12:08:43pm, null] [LOCAL] [dev] [3.12.1] Picking address configured by property 'hazelcast.local.localAddress'
[INFORMACIÓN, 12:08:43pm, null] [LOCAL] [dev] [3.12.1] Picked [172.17.0.1]:5702, using socket ServerSocket[addr=/0:0:0:0:0:0:0:0,localport=5702], bind any local is true
[INFORMACIÓN, 12:08:43pm, null] [172.17.0.1]:5702 [dev] [3.12.1] Hazelcast 3.12.1 (20190611 - 0a0ee66) starting at [172.17.0.1]:5702
[INFORMACIÓN, 12:08:43pm, null] [172.17.0.1]:5702 [dev] [3.12.1] Copyright (c) 2008-2019, Hazelcast, Inc. All Rights Reserved.
[INFORMACIÓN, 12:08:43pm, null] [172.17.0.1]:5702 [dev] [3.12.1] Backpressure is disabled
[INFORMACIÓN, 12:08:43pm, null] [172.17.0.1]:5702 [dev] [3.12.1] Creating MulticastJoiner
[INFORMACIÓN, 12:08:44pm, null] [172.17.0.1]:5702 [dev] [3.12.1] Starting 8 partition threads and 5 generic threads (1 dedicated for priority tasks)
[INFORMACIÓN, 12:08:44pm, null] [172.17.0.1]:5702 [dev] [3.12.1] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
[INFORMACIÓN, 12:08:44pm, null] [172.17.0.1]:5702 [dev] [3.12.1] [172.17.0.1]:5702 is STARTING
[INFORMACIÓN, 12:08:44pm, null] [172.17.0.1]:5702 [dev] [3.12.1] Trying to join to discovered node: [172.17.0.1]:5701
[INFORMACIÓN, 12:08:44pm, null] [172.17.0.1]:5702 [dev] [3.12.1] Connecting to /172.17.0.1:5701, timeout: 10000, bind-any: true
[INFORMACIÓN, 12:08:44pm, null] [172.17.0.1]:5702 [dev] [3.12.1] Initialized new cluster connection between /172.17.0.1:37817 and /172.17.0.1:5701
[INFORMACIÓN, 12:08:50pm, null] [172.17.0.1]:5702 [dev] [3.12.1] 

Members {size:2, ver:2} [
	Member [172.17.0.1]:5701 - 69ba2bb9-a78d-4c62-8b6f-06a59b389524
	Member [172.17.0.1]:5702 - f11299dd-640b-4e55-b94a-42e34e499ffa this
]

[INFORMACIÓN, 12:08:51pm, null] [172.17.0.1]:5702 [dev] [3.12.1] [172.17.0.1]:5702 is STARTED
[INFORMACIÓN, 12:08:51pm, Janus SRE] Space SpaceID [
  type = "SpaceID"
  id = 7ba8885d-545b-445a-a0e9-b655bc15ebe0
  contextID = 2c38fb7f-f363-4f6e-877b-110b1f07cc77
  spaceSpec = interface io.sarl.core.OpenEventSpaceSpecification
] is created
[INFORMACIÓN, 12:08:51pm, Janus SRE] Context 2c38fb7f-f363-4f6e-877b-110b1f07cc77 created
Error when launching Janus: Unable to provision, see the following errors:

1) Error injecting constructor, java.lang.IllegalStateException: Expected the service ZeroMQNetworkService [FAILED] to be RUNNING, but the service has FAILED
  at io.janusproject.kernel.Kernel.<init>(Kernel.java:95)
  at io.janusproject.kernel.Kernel.class(Kernel.java:74)
  while locating io.janusproject.kernel.Kernel

1 error

**Result**
As can be seen, the two kernels found each other and show the pool directions with their respective ports (5701 and 5702). But in the second instance, the Janus kernel crashes and stops.

**System configuration:**
-- SARL version: 0.10.0
-- SARL compiler: 
-  - [ ] Eclipse compiler without Maven	
-  - [ ] Eclipse compiler with Maven	
-  - [x] Maven compiler on the command line	
-  - [ ] sarlc compiler

-- Maven version:
Apache Maven 3.6.0 (97c98ec64a1fdfee7767ce5ffb20918da4f719f3; 2018-10-24T15:41:47-03:00)
Maven home: /opt/maven
Java version: 1.8.0_201, vendor: Oracle Corporation, runtime: /usr/lib/jvm/java-8-oracle/jre
Default locale: es_AR, platform encoding: UTF-8
OS name: "linux", version: "5.0.0-36-generic", arch: "amd64", family: "unix"

-- Java JDK version (with the manufacturer name):
java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)

-- Operating System: Ubuntu 18.04
-  - [x] Linux 64bits	
-  - [ ] Windows 64bits	
-  - [ ] MacOS 64bits

**Comment by gallandarakhneorg** [comment]
Network support will be re-enabled in version 0.12.
