### ISSUE TITLE
Error in running the Boot Agent in SARL 

### ISSUE THREAD

**Issue by charbelmansour** [sarl/sarl#959]
Hello,

I have cloned the github project https://github.com/alexandrelombard/sarl-airsim-interface.git to SARL.

While trying to run the bootAgent of this project I am getting the following error:

Could not find or load main class io.janusproject.Boot
Caused by: java.lang.ClassNotFoundException: io.janusproject.Boot

Thank you for helping us,

Regards,

Charbel

**Comment by gallandarakhneorg** [comment]
The jar file of the Janus SRE must be into the classpath of your application.

**Comment by charbelmansour** [comment]
Okay, thank you.
Regards,
Charbel
