### ISSUE TITLE
Update Janus v3 to make the spawnAgent function in a dedicated thread

### ISSUE THREAD

**Issue by ngaud** [sarl/sarl#960]
Currently the spawnfunction is executed by the thread of the parent caller.
It must extract and isolate in a dedicated thread.

At the same time we have also to study the spawn of multiple agent to see if we continue to emit a single spawnEvent for the whole group thus requiring to wait the end of the spawn and thus the initialize of all agent before sending the event.

**Comment by gallandarakhneorg** [comment]
Done on the `sgallandBranch`.
