### ISSUE TITLE
Missing pom.xml

### ISSUE THREAD

**Issue by charbelmansour** [sarl/sarl#968]
Hello,
We followed these steps:

git clone https://github.com/alexandrelombard/airsim-jvm-api

cd airsim-jvm-api

mvn clean install

When we reached step 3 we obtained the following error:

image1

Can you please give us advice about this issue.
The pom.xml is missing from the project.
Thank you for your help
Best Regards,

**Comment by gallandarakhneorg** [comment]
Use Gradle:
`./gradlew build install`
