### ISSUE TITLE
Problem with multiple initialize event in Behavior inheritance demos

### ISSUE THREAD

**Issue by ngaud** [sarl/sarl#977]
Just a subset of all required initialize clauses are really executed.
See Behavior inheritance demos : it outputs
[INFOS, 10:44:55am, AGENT-f9fec5a8-86df-4068-9247-320df8e0f776] 1: Hello World in the super agent!
[INFOS, 10:44:55am, AGENT-f9fec5a8-86df-4068-9247-320df8e0f776] 2:[i>=0]Parent: This message should be displayed
but 3,4,5 of the child agent are not displayed.

**Comment by ngaud** [comment]
the problem seems to lie in the BehaviorGuardEvaluatorRegistry that didn't return clause from the child class

**Comment by ngaud** [comment]
Could be in the register method

**Comment by ngaud** [comment]
Found : the problem lies in the BehaviorGuardEvaluatorRegistry.register method, by replacing the orignal CopyOnWriteArraySet by a ConcirrentSkipListSet change the behavior of eventSubscribers.addAll(eventMethodsInListener), the used comparator didn't react similarly thus filtering part of the behaviorGuardEvaluator and so preventing the execution of the whole set of necessary methods.

**Comment by ngaud** [comment]
The compareTo method of BehaviorGuardEvaluator wasn't integrating the comparison of method declaring classes that could be different even if targets are equals.

**Comment by ngaud** [comment]
Finally decided to get back to original CopyOnWriteArraySet.
Was unable to tune the compareTo to make it work

**Comment by ngaud** [comment]
Finally decided to get back to original CopyOnWriteArraySet.
Was unable to tune the compareTo to make it work

**Comment by ngaud** [comment]
Finally decided to get back to original CopyOnWriteArraySet.
Was unable to tune the compareTo to make it work

**Comment by ngaud** [comment]
Finally decided to get back to original CopyOnWriteArraySet.
Was unable to tune the compareTo to make it work

**Comment by gallandarakhneorg** [comment]
The code of `BehaviorGuardEvaluatorRegistry` does not correspond to the original code into the repository of Janus 3.
I have discovered that the unregisterListener(Class) is not more present. This miss causes invalid behavior in the rest of the platform.
I will reinject the code and adapt it according to the concurrency policy that is applied in the new code.

**Comment by gallandarakhneorg** [comment]
There is a regression: the version of Janus in the branch is not passing several tests that the orginal version is passing. Some of these tests are related to this issue.
