### ISSUE TITLE
Invalid Java code for a cast of the null value. 

### ISSUE THREAD

**Issue by gallandarakhneorg** [sarl/sarl#996]
Let the code:
```sarl
getResource(null as ClassLoader, path)
```

When the function as multiple definitions with different types as first parameters, the generated Java code is ambiguous because it is:
```java
getResource(null, path)
```

The expected Java code is:
```java
getResource((ClassLoader) null, path)
```

**Comment by gallandarakhneorg** [comment]
The following SARL code generates an error that may be related to this issue:
```sarl
this.object = if (object instanceof MobileObject) object as MobileObject else null
```
The java error on `object as' is: `Java problem: Type mismatch: cannot convert from SituatedObject to MobileObject`.

**Comment by JonathanSamelson** [comment]
I just encountered the same casting issue, and it was not with a null value.

The following code does not compile, A being a superclass of B and C:

```
def fct( param: A){
    if (param instanceof B){
        var param2 = **param** as B
        **onB**(mess)
    } else if (param instanceof C){
       onC(param as C)
    }
}

def onB(param: B){...}
def onC(param: C){...}
```

In the if branch, the compile error is the following: _"Java problem: Type mismatch: cannot convert from A to B"_
In the else if branch the compile error is: _"Java problem: The method onB(B) in the type B is not applicable for the arguments (A)"_
I checked the java generated code, there is indeed no casting.

Oddly, this compile successfully:

```
def fct( param: A){
    if (param instanceof B){
        onB(param as B)
    } 
    if (param instanceof C){
       onC(param as C)
    }
}
```

**Comment by gallandarakhneorg** [comment]
@JonathanSamelson , thank you. Your case will be added into the tests to avoid problems in the next versions. This issue is still open, so that the bug still exists.
